Repository Mailu/Mailu, pull requests merged in 2018-12, with the labels that each got.

#722 Update .mergify.yml
  .mergify.yml
Labels: type/discussion

#728 Fix autobuild
  tests/compose/core/00_create_users.sh
Labels: type/bug

#724 Documentation and examples for traefik
  docs/compose/traefik/docker-compose.yml
  docs/compose/traefik/traefik.toml
  docs/reverse.rst
  optional/traefik-certdumper/.dockerignore
  optional/traefik-certdumper/Dockerfile
  optional/traefik-certdumper/LICENSE
  optional/traefik-certdumper/README.md
  optional/traefik-certdumper/run.sh
  tests/build.yml
Labels: topic/deployment, topic/docs, type/discussion
