Repository Mailu/Mailu, pull requests merged in 2019-01, with the labels that each got.

#792 fix broken webmail and logo url in admin
  CHANGELOG.md
  core/admin/mailu/ui/templates/base.html
  core/admin/mailu/ui/templates/sidebar.html
Labels: type/bug

#797 Upgrade PyYAML
  core/admin/requirements-prod.txt
Labels: type/security

#788 Multiple databases support and postgresql image
  CHANGELOG.md
  core/admin/Dockerfile
  core/admin/mailu/configuration.py
  core/admin/mailu/models.py
  core/admin/migrations/env.py
  core/admin/migrations/versions/049fed905da7_.py
  core/admin/migrations/versions/27ae2f102682_.py
  core/admin/migrations/versions/546b04c886f0_.py
  core/admin/migrations/versions/5aeb5811408e_.py
  core/admin/migrations/versions/9400a032eb1a_.py
  core/admin/migrations/versions/9c28df23f77e_.py
  core/admin/migrations/versions/c162ac88012a_.py
  core/admin/migrations/versions/c9a0b4e653cf_.py
  core/admin/migrations/versions/cd79ed46d9c2_.py
  core/admin/migrations/versions/f1393877871d_.py
  core/admin/migrations/versions/ff0417f4318f_.py
  core/admin/requirements-prod.txt
  core/admin/requirements.txt
  docs/database.rst
  docs/index.rst
  optional/postgresql/Dockerfile
  optional/postgresql/basebackup.sh
  optional/postgresql/conf/pg_hba.conf
  optional/postgresql/conf/pg_ident.conf
  optional/postgresql/conf/postgresql.conf
  optional/postgresql/conf/queries.sql
  optional/postgresql/postgres_crontab
  optional/postgresql/start.py
  setup/flavors/compose/docker-compose.yml
  setup/flavors/compose/mailu.env
  setup/flavors/stack/docker-compose.yml
  setup/server.py
  setup/static/render.js
  setup/templates/steps/database.html
  setup/templates/wizard.html
  tests/build.yml
Labels: review/need2

#799 don't allow negative values on domain creation/edit
  CHANGELOG.md
  core/admin/mailu/manage.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/domain/list.html
  core/admin/mailu/ui/templates/user/signup_domain.html
  core/admin/mailu/ui/views/aliases.py
  core/admin/mailu/ui/views/users.py
  core/admin/migrations/versions/fc099bd15cbe_.py
Labels: review/need2, type/bug, type/enhancement

#854 unbound: drop privileges after binding to port
  CHANGELOG.md
  services/unbound/unbound.conf
Labels: type/enhancement, type/security

#851 Make certdumper output fullchain-pems
  optional/traefik-certdumper/run.sh
Labels: type/backport

#879 Update docs on review dissmissal and automatic rebuilds
  docs/contributors/environment.rst
Labels: type/backport

#882 Fix password validator for creating fetched accounts
  CHANGELOG.md
  core/admin/mailu/manage.py
Labels: type/backport, type/bug
