Repository Mailu/Mailu, pull requests merged in 2019-08, with the labels that each got.

#1078 expose pop3 port, remove imap-ssl from dovecot in kubernetes manifest
  docs/kubernetes/mailu/imap.yaml
Labels: priority/p0

#1134 Only set the redis address once, fixes #1125
  core/admin/mailu/configuration.py
Labels: type/backport

#1130 Remove unnecessary host variable assignments
  core/nginx/config.py
Labels: type/backport

#1141 Docs: fix some build warnings
  docs/cli.rst
  docs/faq.rst
  docs/reverse.rst
Labels: topic/docs, type/backport

#1144 Add proper release notes for 1.7
  docs/releases.rst
Labels: type/backport
