Repository Mailu/Mailu, pull requests merged in 2020-05, with the labels that each got.

#1423 Doc update: proxy_set_header required for admin
  docs/reverse.rst
Labels: topic/docs

#1293 Remove `reject_unverified_recipient` from `smtpd_client_restrictions`
  core/postfix/conf/main.cf
Labels: type/backport

#1481 Postgresql: default SUBNET6 in pg_hba
  optional/postgresql/conf/pg_hba.conf
  towncrier/newsfragments/1479.bug
Labels: priority/p0, type/bug

#1513 Stick radicale to 2.1.12 version
  optional/radicale/Dockerfile
Labels: type/backport
