Repository Mailu/Mailu, pull requests merged in 2020-08, with the labels that each got.

#1542 Remove unused variables
  core/dovecot/start.py
Labels: 1.8, priority/p2, type/enhancement

#1499 Harmonization of the various docker-compose.yml templates
  docs/compose/docker-compose.yml
  setup/flavors/stack/docker-compose.yml
  setup/flavors/stack/setup.html
Labels: priority/p2, type/enhancement

#1538 Introduce environment variable to control dovecot full-text-search
  core/dovecot/conf/dovecot.conf
  docs/compose/.env
  docs/configuration.rst
  setup/flavors/compose/mailu.env
  towncrier/newsfragments/1538.feature
Labels: priority/p1, type/enhancement

#1557 Explicitly define ProxyFix options
  core/admin/mailu/utils.py
Labels: priority/p1, type/bug

#1526 Use Radicale 3.x for webdav service
  optional/radicale/Dockerfile
  optional/radicale/radicale.conf
  towncrier/newsfragments/1512.misc
Labels: priority/p1, type/enhancement

#1511 Setup, compose: add note about reverse DNS
  setup/templates/steps/compose/03_expose.html
Labels: priority/p1, type/enhancement

#1570 Update webmail.yaml
  docs/kubernetes/mailu/webmail.yaml
Labels: flavor/kubernetes, priority/p1, type/enhancement

#1541 alpine 3.12 as base image
  core/admin/Dockerfile
  core/admin/requirements-prod.txt
  core/dovecot/Dockerfile
  core/nginx/Dockerfile
  core/none/Dockerfile
  core/postfix/Dockerfile
  core/rspamd/Dockerfile
  optional/clamav/Dockerfile
  optional/fetchmail/Dockerfile
  optional/fetchmail/fetchmail.py
  optional/postgresql/Dockerfile
  optional/radicale/Dockerfile
  optional/unbound/Dockerfile
Labels: priority/p1, type/enhancement

#1587 Pin test/build pip-dependencies to their last known versions
  tests/requirements.txt
Labels: priority/p0, type/bug
