Repository Mailu/Mailu, pull requests merged in 2021-06, with the labels that each got.

#1833 Switch to github actions for CI/CD
  .github/worfklows/CI.yml
  .travis.yml
  bors.toml
  docs/contributors/environment.rst
  docs/contributors/workflow.rst
  docs/faq.rst
  tests/compose/filters/00_create_users.sh
  tests/deploy.sh
  towncrier/newsfragments/1828.misc
Labels: priority/p0

#1806 Reflect override settings for postfix
  docs/faq.rst
Labels: type/backport

#1694 update compression algorithms for current dovecot
  core/dovecot/conf/dovecot.conf
  docs/compose/.env
  setup/flavors/compose/mailu.env
  tests/compose/core/mailu.env
  tests/compose/fetchmail/mailu.env
  tests/compose/filters/mailu.env
  tests/compose/rainloop/mailu.env
  tests/compose/roundcube/mailu.env
  tests/compose/webdav/mailu.env
  towncrier/newsfragments/1694.feature
Labels: type/enhancement

#1746 DNS records for client autoconfiguration (RFC6186)
  core/admin/mailu/ui/templates/domain/details.html
  towncrier/newsfragments/224.feature
Labels: priority/p2, type/feature

#1836 Test ci parallel
  .github/workflows/CI.yml
  tests/compose/filters/00_create_users.sh
  towncrier/newsfragments/1830.misc
Labels: type/backport

#1754 centralize Webmail authentication behind the admin panel (SSO)
  core/admin/mailu/__init__.py
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/views/base.py
  core/nginx/conf/nginx.conf
  tests/compose/rainloop/mailu.env
  tests/compose/roundcube/mailu.env
  towncrier/newsfragments/783.feature
  webmails/rainloop/Dockerfile
  webmails/rainloop/application.ini
  webmails/rainloop/sso.php
  webmails/rainloop/start.py
  webmails/roundcube/Dockerfile
  webmails/roundcube/config.inc.php
  webmails/roundcube/mailu.php
  webmails/roundcube/start.py
Labels: priority/p1, type/enhancement, type/security
