Repository Mailu/Mailu, pull requests merged in 2021-08, with the labels that each got.

#1851 Upgrade alpine
  core/admin/Dockerfile
  core/dovecot/Dockerfile
  core/nginx/Dockerfile
  core/none/Dockerfile
  core/postfix/Dockerfile
  core/rspamd/Dockerfile
  docs/Dockerfile
  optional/clamav/Dockerfile
  optional/fetchmail/Dockerfile
  optional/postgresql/Dockerfile
  optional/radicale/Dockerfile
  optional/unbound/Dockerfile
  setup/Dockerfile
  towncrier/newsfragments/1851.feature
  webmails/rainloop/Dockerfile
  webmails/roundcube/Dockerfile
Labels: type/backport, type/security

#1877 Fix missing bullet points and styling in documentation
  docs/conf.py
  docs/requirements.txt
Labels: type/backport

#1908 Optimize docs/Dockerfile
  docs/Dockerfile
Labels: type/backport

#1910 Smarter default settings for rate limiting
  core/admin/mailu/configuration.py
  docs/configuration.rst
  setup/templates/steps/config.html
  towncrier/newsfragments/1867.feature
Labels: type/backport

#1912 1.8 release
  .github/workflows/CI.yml
  CHANGELOG.md
  docs/conf.py
  docs/releases.rst
  towncrier/newsfragments/1660.bugfix
  towncrier/newsfragments/1686.bugfix
  towncrier/newsfragments/1720.bugfix
  towncrier/newsfragments/1783.misc
  towncrier/newsfragments/1837.bugfix
  towncrier/newsfragments/1841.feature
  towncrier/newsfragments/1845.feature
  towncrier/newsfragments/1857.doc
  towncrier/newsfragments/1861.bugfix
  towncrier/newsfragments/1867.feature
  towncrier/newsfragments/1874.bugfix
  towncrier/newsfragments/1880.feature
  towncrier/newsfragments/191.bugfix
Labels: type/backport

#1918 Alpine has removed support for btree and hash from postfix
  core/postfix/conf/main.cf
  core/postfix/conf/sasl_passwd
  towncrier/newsfragments/1917.bugfix
Labels: priority/p0, type/bug, type/backport

#1928 Change letsencrypt timer from 1h --> 1 day
  core/nginx/letsencrypt.py
Labels: priority/p2, type/enhancement, python

#1922 Harden postfix's configuration
  core/admin/mailu/internal/nginx.py
  core/nginx/conf/dhparam.pem
  core/nginx/conf/nginx.conf
  core/nginx/conf/tls.conf
  core/nginx/config.py
  core/nginx/letsencrypt.py
  core/postfix/conf/main.cf
  core/postfix/start.py
  docs/configuration.rst
  towncrier/newsfragments/1922.enhancement
Labels: priority/p1, type/security, type/enhancement

#1916 Ratelimit outgoing emails per user
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/views/postfix.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/templates/user/list.html
  core/postfix/conf/main.cf
  core/postfix/conf/master.cf
  core/postfix/start.py
  docs/webadministration.rst
  setup/flavors/compose/mailu.env
  setup/templates/steps/config.html
  towncrier/newsfragments/1031.feature
Labels: priority/p2, type/feature

#1935 Fix bug #1934: logs flooded with "unbound udp connect failed: Address not available for"
  optional/unbound/Dockerfile
Labels: priority/p0, type/bug, type/backport

#1904 Allow specific users to send email from any address
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/views/postfix.py
  docs/configuration.rst
  towncrier/newsfragments/1096.feature
Labels: priority/p2, type/feature

#1902 Make smtp_tls_policy_maps easily configurable
  core/postfix/conf/main.cf
  core/postfix/start.py
  docs/configuration.rst
  towncrier/newsfragments/1558.feature
Labels: priority/p2, type/security, type/feature

#1941 Fix a bug whereby adding new HOSTNAMEs won't necessarily lead to certificates being renewed.
  core/nginx/letsencrypt.py
Labels: priority/p2, type/bug, type/backport

#1939 Ensure that we don't do multiple DNS lookups in the sieve script
  core/dovecot/conf/ham.script
  core/dovecot/conf/spam.script
Labels: priority/p2, type/bug

#1958 Update the documentation on reverse proxies
  docs/compose/traefik/traefik.toml
  docs/reverse.rst
Labels: priority/p2, type/enhancement

#1959 Ensure that we don't trust client headers
  core/nginx/conf/proxy.conf
  docs/configuration.rst
  towncrier/newsfragments/1960.bugfix
Labels: priority/p1, type/security, type/bug
