Repository Mailu/Mailu, pull requests merged in 2021-11, with the labels that each got.

#2029 The Rate-limiter should run after the deny
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
Labels: priority/p2, type/bug

#2032 doh
  core/postfix/conf/main.cf
Labels: priority/p0

#2033 Misc
  core/rspamd/conf/settings.conf
  setup/flavors/compose/docker-compose.yml
  setup/flavors/stack/docker-compose.yml
  towncrier/newsfragments/1705.enhancement
Labels: priority/p2, type/bug

#2036 round display of range inputs to 2 decimals
  core/admin/assets/app.js
Labels: priority/p2, type/enhancement

#2034 Add timezone to containers
  core/admin/Dockerfile
  core/admin/mailu/configuration.py
  core/dovecot/Dockerfile
  core/nginx/Dockerfile
  core/postfix/Dockerfile
  core/rspamd/Dockerfile
  docs/configuration.rst
  optional/clamav/Dockerfile
  optional/fetchmail/Dockerfile
  optional/postgresql/Dockerfile
  optional/radicale/Dockerfile
  optional/traefik-certdumper/Dockerfile
  optional/unbound/Dockerfile
  setup/flavors/compose/mailu.env
  towncrier/newsfragments/1154.enhancement
  webmails/rainloop/Dockerfile
  webmails/roundcube/Dockerfile
  webmails/roundcube/php.ini
Labels: type/enhancement

#2042 Add MESSAGE_RATELIMIT_EXEMPTION
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/views/postfix.py
  docs/configuration.rst
Labels: priority/p2, type/enhancement

#2044 Vault/rspamd: don't return any key for relayed domains
  core/admin/mailu/internal/views/rspamd.py
  core/admin/mailu/sso/views/base.py
Labels: priority/p2, type/enhancement

#2047 Do not call .split() on RELAYNETS if not specified
  core/postfix/conf/main.cf
Labels: priority/p1, type/bug

#1224 RFC: Mailu directory structure
  design/mailu-directory-structure.md
Labels: type/discussion, review/need2

#2037 update python dependencies of admin container
  core/admin/Dockerfile
  core/admin/assets/app.css
  core/admin/assets/app.js
  core/admin/audit.py
  core/admin/mailu/__init__.py
  core/admin/mailu/configuration.py
  core/admin/mailu/debug.py
  core/admin/mailu/models.py
  core/admin/mailu/schemas.py
  core/admin/mailu/sso/templates/form_sso.html
  core/admin/mailu/sso/views/base.py
  core/admin/mailu/ui/templates/alias/list.html
  core/admin/mailu/ui/templates/alternative/list.html
  core/admin/mailu/ui/templates/domain/list.html
  core/admin/mailu/ui/templates/fetch/list.html
  core/admin/mailu/ui/templates/macros.html
  core/admin/mailu/ui/templates/relay/list.html
  core/admin/mailu/ui/templates/token/list.html
  core/admin/mailu/ui/templates/user/list.html
  core/admin/mailu/ui/views/domains.py
  core/admin/mailu/utils.py
  core/admin/migrations/env.py
  core/admin/requirements-prod.txt
  core/admin/requirements.txt
Labels: review/need2, dependencies

#2063 fixed ipv6 access-control
  optional/unbound/unbound.conf
Labels: priority/p1, type/bug

#2066 Upgrade rspamd
  core/rspamd/Dockerfile
  core/rspamd/conf/headers_group.conf
  core/rspamd/conf/settings.conf
Labels: priority/p1, type/enhancement
