Repository Mailu/Mailu, pull requests merged in 2021-12, with the labels that each got.

#2071 Reduce logging level
  core/admin/mailu/utils.py
Labels: priority/p1, type/bug

#2083 Fix Webmail token check. Fix Auth-Port for Webmail. #2079
  core/admin/mailu/internal/nginx.py
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/2079.fix
Labels: priority/p0

#2076 fix the default for DEFER_ON_TLS_ERROR
  core/postfix/start.py
Labels: priority/p0, type/bug

#2084 Fix #2078 (login to webmail did not work when WEB_WEBMAIL=/ was set)
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/2078.fix
Labels: priority/p0

#2072 use dovecot-fts-xapian from alpine package
  core/dovecot/Dockerfile
  towncrier/newsfragments/2072.enhancement
Labels: priority/p1

#2091 Make webmail the default login action
  core/admin/mailu/sso/forms.py
  core/admin/mailu/sso/views/base.py
Labels: priority/p2

#2069 Remove Mailu PostgreSQL
  .github/workflows/CI.yml
  docs/database.rst
  optional/postgresql/Dockerfile
  optional/postgresql/basebackup.sh
  optional/postgresql/conf/pg_hba.conf
  optional/postgresql/conf/pg_ident.conf
  optional/postgresql/conf/postgresql.conf
  optional/postgresql/conf/queries.sql
  optional/postgresql/postgres_crontab
  optional/postgresql/start.py
  setup/README.md
  setup/flavors/compose/docker-compose.yml
  setup/flavors/compose/mailu.env
  setup/flavors/stack/docker-compose.yml
  setup/static/render.js
  setup/templates/steps/database.html
  tests/build.yml
  towncrier/newsfragments/2069.feature
Labels: priority/p0

#2035 updated roundcube to 1.5.1 and carddav to 4.3.0
  docs/compose/docker-compose.yml
  docs/compose/traefik/docker-compose.yml
  docs/configuration.rst
  setup/flavors/compose/docker-compose.yml
  setup/flavors/stack/docker-compose.yml
  towncrier/newsfragments/2035.enhancement
  webmails/roundcube/Dockerfile
  webmails/roundcube/config.inc.php
  webmails/roundcube/healthcheck.sh
  webmails/roundcube/mailu.php
  webmails/roundcube/start.py
Labels: priority/p2, type/enhancement

#2096 Fix missing edit buttons in alias, relay and fetchmail lists in admin.
  core/admin/mailu/ui/templates/alias/list.html
  core/admin/mailu/ui/templates/fetch/list.html
  core/admin/mailu/ui/templates/relay/list.html
  towncrier/newsfragments/2093.fix
Labels: priority/p0

#2094 Sessions tweaks
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
  core/admin/mailu/models.py
  core/admin/mailu/sso/views/languages.py
  core/admin/mailu/utils.py
  docs/configuration.rst
  towncrier/newsfragments/2080.bugfix
  towncrier/newsfragments/2094.bugfix
  webmails/roundcube/config.inc.php
  webmails/roundcube/start.py
Labels: priority/p0

#2098 Sessions tweaks2
  core/admin/mailu/utils.py
  webmails/roundcube/start.py
Labels: priority/p0

#2097 The DB_PORT and ROUNDCUBE_DB_PORT env vars were not used
  docs/configuration.rst
  setup/templates/steps/database.html
  towncrier/newsfragments/2073.bugfix
Labels: priority/p2

#2111 Preparations for 1.9 release
  .github/workflows/CI.yml
  .mergify.yml
  CHANGELOG.md
  RELEASE_TEMPLATE.md
  core/admin/mailu/configuration.py
  docs/conf.py
  docs/faq.rst
  docs/releases.rst
  docs/setup.rst
  towncrier/newsfragments/1031.feature
  towncrier/newsfragments/1037.doc
  towncrier/newsfragments/1096.feature
  towncrier/newsfragments/116.feature
  towncrier/newsfragments/1182.feature
  towncrier/newsfragments/1194.bugfix
  towncrier/newsfragments/1194.feature
  towncrier/newsfragments/1223.bugfix
  towncrier/newsfragments/1294.bugfix
  towncrier/newsfragments/1441.feature
  towncrier/newsfragments/1503.doc
  towncrier/newsfragments/1558.feature
  towncrier/newsfragments/1567.feature
  towncrier/newsfragments/1604.feature
  towncrier/newsfragments/1607.feature
  towncrier/newsfragments/1610.feature
  towncrier/newsfragments/1612.feature
  towncrier/newsfragments/1618.feature
  towncrier/newsfragments/1662.feature
  towncrier/newsfragments/1669.bugfix
  towncrier/newsfragments/1694.feature
  towncrier/newsfragments/1696.misc
  towncrier/newsfragments/1712.misc
  towncrier/newsfragments/1753.feature
  towncrier/newsfragments/1760.bugfix
  towncrier/newsfragments/1764.feature
  towncrier/newsfragments/1798.feature
  towncrier/newsfragments/1828.misc
  towncrier/newsfragments/1830.misc
  towncrier/newsfragments/1831.bugfix
  towncrier/newsfragments/1851.feature
  towncrier/newsfragments/1873.feature
  towncrier/newsfragments/1917.bugfix
  towncrier/newsfragments/1926.feature
  towncrier/newsfragments/1952.bugfix
  towncrier/newsfragments/1960.bugfix
  towncrier/newsfragments/1962.bugfix
  towncrier/newsfragments/1966.feature
  towncrier/newsfragments/1990.bugfix
  towncrier/newsfragments/2069.feature
  towncrier/newsfragments/2073.bugfix
  towncrier/newsfragments/2080.bugfix
  towncrier/newsfragments/2094.bugfix
  towncrier/newsfragments/224.feature
  towncrier/newsfragments/360.bugfix
  towncrier/newsfragments/466.feature
  towncrier/newsfragments/470.doc
  towncrier/newsfragments/783.feature
Labels: review/need2

#2116 fix 2114: redirect old path
  core/admin/mailu/ui/views/base.py
Labels: priority/p1, type/bug
