Repository Mailu/Mailu, pull requests merged in 2021-03, with the labels that each got.

#1763 show flash messages again
  core/admin/mailu/ui/templates/base.html
Labels: type/backport

#1765 Set sensible cookie flags on the admin app
  core/admin/mailu/configuration.py
  docs/configuration.rst
Labels: type/backport

#1783 Switch to server-side sessions
  core/admin/mailu/__init__.py
  core/admin/mailu/configuration.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/views/base.py
  core/admin/mailu/ui/views/users.py
  core/admin/requirements-prod.txt
  core/admin/requirements.txt
  docs/configuration.rst
  towncrier/newsfragments/1783.misc
Labels: priority/p1, type/backport, type/bug, type/security

#1785 Fix bug #1660 (don't replace nested headers)
  core/postfix/conf/master.cf
  towncrier/newsfragments/1660.bugfix
Labels: priority/p1, type/backport, type/bug

#1761 check for `ipv6_enabled` in the compose template
  setup/flavors/compose/docker-compose.yml
Labels: type/bug

#1792 Update fail2ban documentation
  docs/faq.rst
Labels: type/enhancement
