Repository Mailu/Mailu, pull requests merged in 2021-09, with the labels that each got.

#1965 postfix/tls_policy: Use lmdb map instead of hash
  core/postfix/conf/main.cf
Labels: priority/p0, type/bug

#1800 AdminLTE 3
  core/admin/Dockerfile
  core/admin/assets/app.css
  core/admin/assets/app.js
  core/admin/assets/vendor.js
  core/admin/mailu/ui/templates/admin/create.html
  core/admin/mailu/ui/templates/admin/list.html
  core/admin/mailu/ui/templates/alias/create.html
  core/admin/mailu/ui/templates/alias/list.html
  core/admin/mailu/ui/templates/alternative/list.html
  core/admin/mailu/ui/templates/announcement.html
  core/admin/mailu/ui/templates/base.html
  core/admin/mailu/ui/templates/client.html
  core/admin/mailu/ui/templates/confirm.html
  core/admin/mailu/ui/templates/domain/create.html
  core/admin/mailu/ui/templates/domain/details.html
  core/admin/mailu/ui/templates/domain/list.html
  core/admin/mailu/ui/templates/domain/signup.html
  core/admin/mailu/ui/templates/fetch/create.html
  core/admin/mailu/ui/templates/fetch/list.html
  core/admin/mailu/ui/templates/form.html
  core/admin/mailu/ui/templates/macros.html
  core/admin/mailu/ui/templates/manager/create.html
  core/admin/mailu/ui/templates/manager/list.html
  core/admin/mailu/ui/templates/relay/list.html
  core/admin/mailu/ui/templates/sidebar.html
  core/admin/mailu/ui/templates/token/list.html
  core/admin/mailu/ui/templates/user/create.html
  core/admin/mailu/ui/templates/user/forward.html
  core/admin/mailu/ui/templates/user/list.html
  core/admin/mailu/ui/templates/user/reply.html
  core/admin/mailu/ui/templates/user/settings.html
  core/admin/mailu/ui/templates/user/signup.html
  core/admin/mailu/ui/views/__init__.py
  core/admin/mailu/ui/views/languages.py
  core/admin/mailu/utils.py
  core/admin/package.json
  core/admin/webpack.config.js
  towncrier/newsfragments/1567.feature
  towncrier/newsfragments/1764.feature
Labels: priority/p2, type/enhancement

#1961 Implement MTA-STS and DANE validation
  README.md
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/views/postfix.py
  core/admin/mailu/utils.py
  core/postfix/Dockerfile
  core/postfix/conf/main.cf
  core/postfix/mta-sts-daemon.yml
  core/postfix/start.py
  docs/configuration.rst
  docs/faq.rst
  towncrier/newsfragments/1798.feature
Labels: priority/p2, type/feature

#1967 fix 1789: ensure that nginx resolves ipv4 addresses
  core/nginx/conf/nginx.conf
Labels: priority/p1, type/bug, type/backport

#1968 optimize handle_authentication
  core/admin/mailu/internal/nginx.py
Labels: type/bug, type/backport

#1976 fix spelling in PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: type/backport

#1975 Replace traceback with error message when creating initial admin user
  core/admin/mailu/manage.py
Labels: type/backport

#1980 fix freshclam startup
  optional/clamav/conf/freshclam.conf
Labels: priority/p1, type/bug, type/backport

#1971 Updated Polish translation.
  core/admin/mailu/translations/pl/LC_MESSAGES/messages.po
Labels: type/enhancement

#1989 Fix #1988
  core/admin/mailu/utils.py
Labels: priority/p0, type/bug

#1998 Fix healthcheck
  webmails/roundcube/Dockerfile
  webmails/roundcube/mailu.php
  webmails/roundcube/start.py
Labels: type/bug
