Repository Mailu/Mailu, pull requests merged in 2021-07, with the labels that each got.

#1843 fix bugs in model and schema introduced by #1604
  core/admin/mailu/models.py
  core/admin/mailu/schemas.py
Labels: priority/p0, type/bug

#1841 Update version of roundcube webmail and carddav plugin.
  towncrier/1841.feature
  webmails/roundcube/Dockerfile
Labels: type/backport, type/security

#1666 Update front.yaml
  docs/kubernetes/mailu/front.yaml
Labels: type/backport

#1849 Server-side session enhancements
  core/admin/mailu/__init__.py
  core/admin/mailu/configuration.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/views/base.py
  core/admin/mailu/ui/views/users.py
  core/admin/mailu/utils.py
  docs/configuration.rst
  docs/faq.rst
  towncrier/newsfragments/1783.misc
Labels: type/security

#1853 Update dependencies
  core/admin/Dockerfile
  core/admin/requirements-prod.txt
Labels: type/backport, type/security

#1852 Improve ci
  .github/workflows/CI.yml
  tests/deploy.sh
Labels: type/backport

#1845 Update rainloop to 1.16.0
  towncrier/newsfragments/1845.feature
  webmails/rainloop/Dockerfile
Labels: type/backport, type/security

#1862 fix #1861: allow colons in passwords: fix the parsing of http-basic auth headers
  core/admin/mailu/internal/views/auth.py
  towncrier/newsfragments/1861.bugfix
Labels: type/backport, type/bug

#1858 Docs: Replace hardcoded journald logpath with systemd backend
  PULL_REQUEST_TEMPLATE.md
  docs/faq.rst
  towncrier/newsfragments/1857.doc
Labels: type/backport, type/enhancement

#1857 disable startdate when autoreply is disabled
  core/admin/mailu/ui/templates/user/reply.html
Labels: type/backport, type/bug

#1874 Remove dot in blueprint name to prevent critical flask error
  setup/server.py
  towncrier/newsfragments/1874.bugfix
Labels: priority/p0, type/backport, type/bug

#1871 Replace PUBLIC_HOSTNAME/IP with real data in Received headers
  core/postfix/conf/outclean_header_filter.cf
  core/postfix/start.py
  towncrier/newsfragments/191.bugfix
Labels: priority/p1, type/backport

#1880 Update jquery dependency of setup and set pinned versions
  setup/requirements.txt
  setup/templates/steps/compose/02_services.html
  setup/templates/steps/config.html
  setup/templates/steps/stack/02_services.html
  towncrier/newsfragments/1880.feature
Labels: type/backport

#1886 Fix 1294: ensure podop's socket is owned by postfix
  core/postfix/start.py
  towncrier/newsfragments/1294.bugfix
Labels: type/bug

#1887 Docs: Limit fail2ban matches to front container
  docs/faq.rst
Labels: type/backport

#1890 fix Email class in model.py
  core/admin/mailu/models.py
Labels: priority/p1, type/bug

#1885 fix 1884: always lookup a FQDN
  core/postfix/start.py
Labels: flavor/kubernetes, priority/p1, type/backport, type/bug

#1891 fix TypeDecorators IdnaDomain and JSONEncoded
  core/admin/mailu/manage.py
  core/admin/mailu/models.py
  towncrier/newsfragments/1891.bugfix
Labels: priority/p2, type/bug

#1888 Use threads in gunicorn rather than workers/processes
  core/admin/start.py
Labels: priority/p2, type/backport, type/enhancement

#1896 save dkim key after creation
  core/admin/mailu/models.py
  core/admin/mailu/ui/views/domains.py
Labels: priority/p1, type/bug

#1856 update asset builder dependencies
  core/admin/package.json
Labels: dependencies, type/backport

#1901 treat localpart case insensitive again
  core/admin/mailu/models.py
Labels: priority/p1, type/bug
