Repository Mailu/Mailu, pull requests merged in 2022-05, with the labels that each got.

#2332 Correct typo
  docs/contributors/memo.rst
Labels: type/documentation

#2336 helm-chart is now in sync; update the wording
  CHANGELOG.md
  docs/maintain.rst
  docs/releases.rst
Labels: type/backport, type/documentation

#2348 Silence some errors in nginx
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/2346.bugfix
Labels: priority/p2, type/bug, type/backport

#2338 Update X-XSS-Protection to current recommendation
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/2338.misc
Labels: priority/p2, type/security, type/enhancement

#2278 Feature: Ability to change marking spam emails as "Read"
  core/admin/mailu/internal/templates/default.sieve
  core/admin/mailu/manage.py
  core/admin/mailu/models.py
  core/admin/mailu/translations/ca/LC_MESSAGES/messages.po
  core/admin/mailu/translations/da/LC_MESSAGES/messages.po
  core/admin/mailu/translations/de/LC_MESSAGES/messages.po
  core/admin/mailu/translations/en/LC_MESSAGES/messages.po
  core/admin/mailu/translations/es/LC_MESSAGES/messages.po
  core/admin/mailu/translations/eu/LC_MESSAGES/messages.po
  core/admin/mailu/translations/fr/LC_MESSAGES/messages.po
  core/admin/mailu/translations/he/LC_MESSAGES/messages.po
  core/admin/mailu/translations/hu/LC_MESSAGES/messages.po
  core/admin/mailu/translations/is/LC_MESSAGES/messages.po
  core/admin/mailu/translations/it/LC_MESSAGES/messages.po
  core/admin/mailu/translations/ja/LC_MESSAGES/messages.po
  core/admin/mailu/translations/nb_NO/LC_MESSAGES/messages.po
  core/admin/mailu/translations/nl/LC_MESSAGES/messages.po
  core/admin/mailu/translations/pl/LC_MESSAGES/messages.po
  core/admin/mailu/translations/pt/LC_MESSAGES/messages.po
  core/admin/mailu/translations/ru/LC_MESSAGES/messages.po
  core/admin/mailu/translations/sv/LC_MESSAGES/messages.po
  core/admin/mailu/translations/zh/LC_MESSAGES/messages.po
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/user/settings.html
  core/admin/messages.pot
  core/admin/migrations/versions/8f9ea78776f4_.py
  docs/cli.rst
  towncrier/newsfragments/2278.feature
Labels: priority/p2, type/feature

#2325 postfix: wrap IPv6 CIDRs in square brackets for RELAYNETS
  core/postfix/start.py
  towncrier/newsfragments/2325.bugfix
Labels: priority/p1, type/bug, type/backport
