Repository Mailu/Mailu, pull requests merged in 2022-10, with the labels that each got.

#2448 Give a chance to rspamd's bayes classifier
  core/rspamd/conf/classifier-bayes.conf
  docs/antispam.rst
  docs/faq.rst
  towncrier/newsfragments/2447.bugfix
Labels: priority/p1, type/bug, type/backport, type/documentation

#2468 Ensure that Mailu keeps working even if it can't obtain a certificate from LE
  core/nginx/letsencrypt.py
  towncrier/newsfragments/2467.bugfix
Labels: priority/p1, type/bug, type/backport

#2480 Fix a bunch of typos
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/schemas.py
  core/admin/mailu/translations/ca/LC_MESSAGES/messages.po
  core/admin/mailu/translations/da/LC_MESSAGES/messages.po
  core/admin/mailu/translations/de/LC_MESSAGES/messages.po
  core/admin/mailu/translations/en/LC_MESSAGES/messages.po
  core/admin/mailu/translations/es/LC_MESSAGES/messages.po
  core/admin/mailu/translations/eu/LC_MESSAGES/messages.po
  core/admin/mailu/translations/fr/LC_MESSAGES/messages.po
  core/admin/mailu/translations/he/LC_MESSAGES/messages.po
  core/admin/mailu/translations/hu/LC_MESSAGES/messages.po
  core/admin/mailu/translations/is/LC_MESSAGES/messages.po
  core/admin/mailu/translations/it/LC_MESSAGES/messages.po
  core/admin/mailu/translations/ja/LC_MESSAGES/messages.po
  core/admin/mailu/translations/nb_NO/LC_MESSAGES/messages.po
  core/admin/mailu/translations/nl/LC_MESSAGES/messages.po
  core/admin/mailu/translations/pl/LC_MESSAGES/messages.po
  core/admin/mailu/translations/pt/LC_MESSAGES/messages.po
  core/admin/mailu/translations/ru/LC_MESSAGES/messages.po
  core/admin/mailu/translations/sv/LC_MESSAGES/messages.po
  core/admin/mailu/translations/zh/LC_MESSAGES/messages.po
  core/admin/mailu/ui/templates/relay/edit.html
  core/admin/mailu/utils.py
  core/admin/messages.pot
  core/admin/start.py
  core/dovecot/conf/dovecot.conf
  core/nginx/conf/nginx.conf
  docs/antispam.rst
  docs/arm_images.rst
  docs/compose/.env
  docs/compose/requirements.rst
  docs/compose/setup.rst
  docs/configuration.rst
  docs/contributors/guidelines.rst
  docs/contributors/workflow.rst
  docs/dns.rst
  docs/faq.rst
  docs/releases.rst
  docs/swarm/1.5/README.md
  docs/swarm/master/README.md
  docs/swarm/master/README_nfs_example.md
  docs/webadministration.rst
  setup/README.md
  setup/templates/setup.html
  setup/templates/steps/compose/03_expose.html
  tests/compose/core/00_create_users.sh
  webmails/roundcube/config.inc.php
  webmails/roundcube/start.py
Labels: type/documentation

#2486 Quote SMTP SIZE to avoid splitting keyword and parameter in EHLO response
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/2485.bugfix
Labels: priority/p1, type/bug, type/backport

#2458 Fix: Don't update updated_at on quota_bytes_used change
  core/admin/mailu/internal/views/dovecot.py
  core/admin/mailu/internal/views/fetch.py
  core/admin/mailu/models.py
  towncrier/newsfragments/1363.bugfix
Labels: priority/p2, type/bug

#2328 Feature: Configurable default spam threshold used for new users
  core/admin/mailu/configuration.py
  core/admin/mailu/models.py
  docs/antispam.rst
  docs/configuration.rst
  setup/flavors/compose/mailu.env
  towncrier/newsfragments/2328.feature
Labels: type/enhancement

#2501 Fix armv7 build by manually downloading crates.io index
  core/base/Dockerfile
Labels: priority/p0, type/bug
