Repository Mailu/Mailu, pull requests merged in 2022-02, with the labels that each got.

#2206 Patch function "Display Name" into admin page
  core/admin/mailu/ui/templates/sidebar.html
Labels: type/enhancement

#2211 Ensure we use IMAP IDLE like it's supposed to work
  core/dovecot/conf/dovecot.conf
  towncrier/newsfragments/2211.misc
Labels: priority/p1, type/enhancement

#2234 fix #2220
  core/admin/package.json
Labels: priority/p0, type/bug, type/backport

#2196 roundcube-carddav : Use des_key for pwstore_scheme
  towncrier/newsfragments/2196.bugfix
  webmails/roundcube/Dockerfile
  webmails/roundcube/config.inc.carddav.php
Labels: priority/p1, type/bug, type/backport

#2207 Update webmail container configuration to support MESSAGE_SIZE_LIMIT
  towncrier/newsfragments/2207.bugfix
  webmails/rainloop/Dockerfile
  webmails/rainloop/config.py
  webmails/rainloop/config/nginx-rainloop.conf
  webmails/rainloop/start.py
Labels: priority/p1, type/bug, type/backport

#2195 roundcube: Add /overrides directory in include
  docs/faq.rst
  towncrier/newsfragments/2195.bugfix
  webmails/roundcube/config.inc.php
Labels: type/bug, type/backport

#2248 Manual backport of #2207
  towncrier/newsfragments/2207.bugfix
  webmails/rainloop/Dockerfile
  webmails/rainloop/config.py
  webmails/rainloop/config/nginx-rainloop.conf
  webmails/rainloop/start.py
Labels: priority/p1, type/bug

#2251 Fix broken setup. Not all dependencies were pinned. As usual a depend…
  setup/requirements.txt
  towncrier/newsfragments/2249.bugfix
Labels: priority/p0, type/backport

#2253 Workaround the infamous coredns feature
  core/admin/mailu/utils.py
  core/admin/start.py
  docs/faq.rst
  setup/static/render.js
  setup/templates/steps/compose/03_expose.html
  towncrier/newsfragments/2239.bugfix
Labels: priority/p1, type/bug, type/backport

#2254 Send ISRG_X1 on port 25, make DANE pin that
  core/admin/mailu/models.py
  core/nginx/conf/nginx.conf
  core/nginx/config.py
  core/nginx/letsencrypt.py
Labels: priority/p0, type/bug, type/backport
