Repository Mailu/Mailu, pull requests merged in 2022-11, with the labels that each got.

#2513 fix(auto-reply): include start and end dates in the auto-reply period
  core/admin/mailu/models.py
  towncrier/newsfragments/2512.bugfix
Labels: priority/p1, type/bug, type/backport

#2498 Implement ITERATE in podop
  core/admin/mailu/internal/views/dovecot.py
  core/base/libs/podop/podop/dovecot.py
  core/dovecot/conf/auth.conf
  towncrier/newsfragments/2498.feature
Labels: priority/p2, type/feature

#2518 Add dev runner for admin container
  core/admin/.gitignore
  core/admin/assets/Dockerfile
  core/admin/assets/assets/app.css
  core/admin/assets/assets/app.js
  core/admin/assets/assets/mailu.png
  core/admin/assets/assets/vendor.js
  core/admin/assets/package.json
  core/admin/assets/webpack.config.js
  core/admin/mailu/__init__.py
  core/admin/mailu/configuration.py
  core/admin/run_dev.sh
  docs/contributors/environment.rst
Labels: type/feature

#2500 Password policy enforcement
  core/admin/assets/assets/app.js
  core/admin/mailu/sso/forms.py
  core/admin/mailu/sso/templates/form_sso.html
  core/admin/mailu/sso/views/base.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/macros.html
  core/admin/mailu/ui/views/domains.py
  core/admin/mailu/ui/views/users.py
  core/admin/mailu/utils.py
  towncrier/newsfragments/2500.feature
Labels: priority/p2, type/feature

#2157 configure datatables via html5 data attributes
  core/admin/mailu/__init__.py
  core/admin/mailu/sso/templates/base_sso.html
  core/admin/mailu/sso/templates/sidebar_sso.html
  core/admin/mailu/ui/templates/admin/list.html
  core/admin/mailu/ui/templates/alias/list.html
  core/admin/mailu/ui/templates/alternative/list.html
  core/admin/mailu/ui/templates/base.html
  core/admin/mailu/ui/templates/client.html
  core/admin/mailu/ui/templates/domain/list.html
  core/admin/mailu/ui/templates/fetch/list.html
  core/admin/mailu/ui/templates/macros.html
  core/admin/mailu/ui/templates/manager/list.html
  core/admin/mailu/ui/templates/relay/list.html
  core/admin/mailu/ui/templates/token/list.html
  core/admin/mailu/ui/templates/user/list.html
  core/admin/mailu/ui/templates/user/signup_domain.html
Labels: type/bug, type/backport

#2479 Rework the anti-spoofing rule
  README.md
  core/admin/mailu/internal/views/postfix.py
  core/admin/mailu/internal/views/rspamd.py
  core/postfix/conf/main.cf
  core/postfix/start.py
  core/rspamd/conf/force_actions.conf
  core/rspamd/conf/multimap.conf
  core/rspamd/conf/whitelist.conf
  core/rspamd/start.py
  docs/index.rst
  towncrier/newsfragments/2475.feature
Labels: type/feature

#2523 fix JS error
  core/admin/assets/assets/app.js
Labels: priority/p1, type/bug

#2514 Update deps
  core/admin/mailu/ui/forms.py
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
Labels: dependencies, python

#2532 Allow JS debugging, speed-up asset-build, disable redirect-debug.
  core/admin/assets/Dockerfile
  core/admin/assets/assets/app.js
  core/admin/assets/assets/vendor.js
  core/admin/assets/webpack.config.js
  core/admin/mailu/configuration.py
  core/admin/run_dev.sh
Labels: python

#2537 Fix the armv7 build (again)!
  core/base/Dockerfile
Labels: priority/p0, type/bug

#2538 Fix the ARM build again
  core/base/Dockerfile
Labels: priority/p0, type/bug

#2545 Don't force a password reset
  core/admin/mailu/ui/views/users.py
Labels: priority/p0, type/bug

#2547 Disable libhardened-malloc for non x86.
  core/base/Dockerfile
Labels: priority/p0, type/bug

#2529 Improve fetchmail
  core/admin/mailu/internal/views/fetch.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/fetch/create.html
  core/admin/mailu/ui/templates/fetch/list.html
  core/admin/mailu/ui/views/fetches.py
  core/admin/mailu/ui/views/users.py
  core/admin/mailu/utils.py
  core/admin/migrations/versions/f4f0f89e0047_.py
  docs/webadministration.rst
  optional/fetchmail/fetchmail.py
  setup/flavors/compose/docker-compose.yml
  towncrier/newsfragments/1231.bugfix
  towncrier/newsfragments/2246.bugfix
  towncrier/newsfragments/711.feature
Labels: priority/p2, type/enhancement

#2526 Upgrade Snappymail to 2.21 and merge the webmail containers
  .github/workflows/build_test_deploy.yml
  setup/flavors/compose/docker-compose.yml
  setup/flavors/stack/docker-compose.yml
  tests/build.hcl
  tests/compose/roundcube/docker-compose.yml
  tests/compose/roundcube/mailu.env
  tests/compose/webmail/01_ensure_admin_unreachable.sh
  tests/compose/webmail/docker-compose.yml
  tests/compose/webmail/mailu.env
  towncrier/newsfragments/2526.misc
  webmails/Dockerfile
  webmails/nginx-webmail.conf
  webmails/php-webmail.conf
  webmails/php.ini
  webmails/roundcube/Dockerfile
  webmails/roundcube/config/config.inc.php
  webmails/roundcube/config/php-roundcube.conf
  webmails/roundcube/login/mailu.php
  webmails/roundcube/pubkey.asc
  webmails/snappymail/Dockerfile
  webmails/snappymail/config.py
  webmails/snappymail/config/nginx-snappymail.conf
  webmails/snappymail/defaults/application.ini
  webmails/snappymail/defaults/default.ini
  webmails/snappymail/defaults/default.json
  webmails/snappymail/defaults/php.ini
  webmails/snappymail/login/sso.php
  webmails/snappymail/pubkey.asc
  webmails/snappymail/start.py
  webmails/start.py
Labels: priority/p2, type/security, type/enhancement

#2539 Upgrade alpine, make setup use the base image
  .github/workflows/build_test_deploy.yml
  core/admin/start.py
  core/base/Dockerfile
  core/none/Dockerfile
  core/rspamd/start.py
  setup/Dockerfile
  setup/requirements.txt
  tests/build.hcl
  tests/compose/filters/02_email_antispam.sh
  towncrier/newsfragments/2539.misc
Labels: priority/p2, type/security, type/enhancement

#2543 Fix #2231: make public announcements work
  core/admin/mailu/models.py
  core/admin/mailu/ui/views/base.py
  towncrier/newsfragments/2231.bugfix
Labels: priority/p1, type/bug, type/backport

#2554 Rollback to mysql-connector-python==8.0.29
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
Labels: priority/p0, type/bug

#2556 deprecate swarm in 1.9
  docs/swarm/master/README.md
  setup/templates/steps/flavor.html
Labels: flavor/swarm, type/documentation

#2546 Implement a GUI for WILDCARD_SENDERS
  core/admin/mailu/internal/views/postfix.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/macros.html
  core/admin/mailu/ui/templates/user/create.html
  core/admin/mailu/ui/templates/user/list.html
  core/admin/migrations/versions/7ac252f2bbbf_.py
  docs/webadministration.rst
  towncrier/newsfragments/2372.feature
Labels: priority/p2, type/feature

#2557 Remove Swarm from master
  docs/contributors/environment.rst
  docs/contributors/guidelines.rst
  docs/faq.rst
  docs/swarm/1.5/README.md
  docs/swarm/master/README.md
  docs/swarm/master/README_nfs_example.md
  setup/flavors/stack/docker-compose.yml
  setup/flavors/stack/mailu.env
  setup/flavors/stack/setup.html
  setup/server.py
  setup/templates/steps/compose/02_services.html
  setup/templates/steps/compose/03_expose.html
  setup/templates/steps/config.html
  setup/templates/steps/flavor.html
  setup/templates/steps/stack/02_services.html
  setup/templates/steps/stack/03_expose.html
  setup/templates/wizard.html
Labels: flavor/swarm, type/documentation

#2561 set the umask when using config-export
  core/admin/mailu/manage.py
Labels: type/security, type/enhancement

#2563 Close #1483: remove postfix's /queue/pid/master.pid
  core/postfix/start.py
  towncrier/newsfragments/1483.bugfix
Labels: priority/p1, type/bug

#2567 Remove the dependency on pyOpenSSL
  core/admin/mailu/dkim.py
  core/admin/mailu/schemas.py
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
Labels: priority/p2, type/enhancement

#2568 Fix a bug preventing users without IMAP access to access the webmails
  core/admin/mailu/internal/nginx.py
  towncrier/newsfragments/2451.bugfix
Labels: priority/p1, type/bug, type/backport
