Repository Mailu/Mailu, pull requests merged in 2022-04, with the labels that each got.

#2299 admin: graceful fail on user fetch in basic auth
  core/admin/mailu/internal/views/auth.py
Labels: priority/p2, type/bug, type/backport, python

#2302 Update alpine-linux to 3.14.5 - Zlib security FIX
  core/admin/Dockerfile
  core/dovecot/Dockerfile
  core/nginx/Dockerfile
  core/none/Dockerfile
  core/postfix/Dockerfile
  optional/clamav/Dockerfile
  optional/fetchmail/Dockerfile
  optional/radicale/Dockerfile
  optional/unbound/Dockerfile
  setup/Dockerfile
  towncrier/newsfragments/2302.bugfix
Labels: priority/p1, type/security, type/backport

#2305 Adding missing semicolon after remote_addr
  docs/reverse.rst
Labels: type/backport, type/documentation

#2317 Add pytz module to webdav container
  optional/radicale/Dockerfile
Labels: priority/p2, type/bug, type/backport

#2323 Fix Postfix FileExistsError on startup
  core/postfix/start.py
Labels: priority/p1, type/bug, type/backport

#2331 Add data/fetchmail to mkdir command
  setup/flavors/stack/setup.html
Labels: priority/p2, type/documentation
