Repository Mailu/Mailu, pull requests merged in 2022-12, with the labels that each got.

#2565 Fix DB downgrade
  core/admin/migrations/versions/f4f0f89e0047_.py
Labels: type/bug

#2571 Upgrade to alpine 3.17.0
  core/base/Dockerfile
  towncrier/newsfragments/2570.misc
  webmails/Dockerfile
Labels: type/enhancement

#2577 Autofocus the login form on /sso/login
  core/admin/mailu/sso/forms.py
  towncrier/newsfragments/2577.misc
Labels: priority/p2, type/enhancement

#2580 Fixed roundcube carddav module
  webmails/Dockerfile
  webmails/snuffleupagus.rules
Labels: type/bug

#2562 Dynamic address resolution everywhere
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/templates/client.html
  core/admin/run_dev.sh
  core/admin/start.py
  core/base/Dockerfile
  core/base/libs/socrate/socrate/system.py
  core/base/libs/socrate/test.py
  core/dovecot/conf/ham.script
  core/dovecot/conf/spam.script
  core/dovecot/start.py
  core/nginx/conf/nginx.conf
  core/nginx/config.py
  core/postfix/conf/main.cf
  core/postfix/start.py
  core/rspamd/conf/antivirus.conf
  core/rspamd/start.py
  docs/configuration.rst
  optional/fetchmail/fetchmail.py
  optional/unbound/start.py
  setup/flavors/compose/docker-compose.yml
  towncrier/newsfragments/1341.misc
  webmails/start.py
Labels: type/enhancement

#2587 fix roundcube/sieve
  webmails/Dockerfile
  webmails/roundcube/roundcube.diff
Labels: priority/p1, type/bug

#2591 Add button to mailu-admin in roundcube task menu
  core/admin/mailu/ui/templates/sidebar.html
  towncrier/2591.feature
  webmails/Dockerfile
  webmails/roundcube/config/config.inc.php
  webmails/roundcube/login/localization/en_US.inc
  webmails/roundcube/login/mailu.php
  webmails/roundcube/login/skins/classic/mailu.css
  webmails/roundcube/login/skins/elastic/mailu.css
  webmails/roundcube/login/skins/larry/mailu.css
Labels: priority/p2, type/feature

#2593 Drop postfix rsyslog localhost messages with IPv6 address
  core/postfix/conf/rsyslog.conf
  towncrier/newsfragments/2594.feature
Labels: priority/p2, type/enhancement

#2588 IMAP folder names may contain characters outside of \w: [a-zA-Z0-9]
  core/admin/mailu/ui/forms.py
Labels: priority/p1, type/bug

#2528 Implement #2510: oletools integration
  .github/workflows/build_test_deploy.yml
  README.md
  core/base/Dockerfile
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
  core/oletools/Dockerfile
  core/rspamd/conf/composites.conf
  core/rspamd/conf/external_services.conf
  core/rspamd/conf/external_services_group.conf
  core/rspamd/conf/forbidden_file_extension.map
  core/rspamd/conf/multimap.conf
  docs/antispam.rst
  docs/configuration.rst
  docs/index.rst
  setup/flavors/compose/docker-compose.yml
  setup/flavors/compose/mailu.env
  setup/templates/steps/compose/02_services.html
  setup/templates/steps/config.html
  tests/build.hcl
  tests/compose/core/docker-compose.yml
  tests/compose/core/mailu.env
  tests/compose/fetchmail/docker-compose.yml
  tests/compose/fetchmail/mailu.env
  tests/compose/filters/01_email_test.sh
  tests/compose/filters/03_email_macro.sh
  tests/compose/filters/2003x32_word_msgbox_stomped_fakecode.doc
  tests/compose/filters/docker-compose.yml
  tests/compose/filters/eicar.com.txt
  tests/compose/filters/excel4_sample_macro.slk
  tests/compose/filters/mailu.env
  tests/compose/webdav/docker-compose.yml
  tests/compose/webdav/mailu.env
  tests/compose/webmail/docker-compose.yml
  tests/compose/webmail/mailu.env
  towncrier/newsfragments/2510.feature
  towncrier/newsfragments/2511.misc
Labels: priority/p2, type/feature

#2598 drop privs better
  core/admin/start.py
  core/base/libs/socrate/socrate/system.py
  core/dovecot/start.py
  core/postfix/start.py
  optional/fetchmail/fetchmail.py
  webmails/start.py
Labels: priority/p1, type/bug

#2601 Fix creation of deep structures using import in update mode
  core/admin/mailu/schemas.py
  towncrier/newsfragments/2601.bugfix
Labels: priority/p0, type/bug, type/backport, python

#2605 Reduce the SSL session caches from 50m each to 3m each
  core/nginx/conf/nginx.conf
  core/nginx/conf/tls.conf
  towncrier/newsfragments/2605.misc
Labels: priority/p2, type/enhancement

#2607 Update python dependencies as suggested by dependabot
  core/admin/run_dev.sh
  core/base/requirements-build.txt
  core/base/requirements-prod.txt
Labels: type/security, dependencies, python

#2596 db.String without length cause an error in migration for MySQL DB
  core/admin/mailu/models.py
Labels: type/bug, type/backport

#2603 Enable HAPROXY protocol on SUBNET
  core/admin/mailu/internal/views/dovecot.py
  core/dovecot/conf/dovecot.conf
  core/nginx/conf/nginx.conf
  core/postfix/Dockerfile
  core/postfix/conf/main.cf
  core/postfix/conf/master.cf
  towncrier/newsfragments/2603.bugfix
Labels: type/bug
