Repository Mailu/Mailu, pull requests merged in 2022-01, with the labels that each got.

#2119 Fix #2117. Gpg-agent package was missing for roundcube image.
  docs/releases.rst
  towncrier/newsfragments/2117.bugfix
  webmails/roundcube/Dockerfile
Labels: priority/p1, type/bug, type/backport

#2121 Update CHANGELOG.md with items that were not added by mistake.
  CHANGELOG.md
  towncrier/newsfragments/1154.enhancement
  towncrier/newsfragments/1638.fix
  towncrier/newsfragments/1705.enhancement
  towncrier/newsfragments/1922.enhancement
  towncrier/newsfragments/1929.enhancement
  towncrier/newsfragments/1992.enhancement
  towncrier/newsfragments/1996.enhancement
  towncrier/newsfragments/2002.enhancement
  towncrier/newsfragments/2007.enhancement
  towncrier/newsfragments/2017.enhancement
  towncrier/newsfragments/2035.enhancement
  towncrier/newsfragments/2072.enhancement
  towncrier/newsfragments/2078.fix
  towncrier/newsfragments/2079.fix
  towncrier/newsfragments/2093.fix
  towncrier/newsfragments/2102.fix
  towncrier/newsfragments/2106.fix
  towncrier/newsfragments/2121.misc
  towncrier/newsfragments/224.enhancement
Labels: priority/p2, type/backport

#2130 Fix 2125: Make the caller responsible to know whether the rate-limit code should be called or not
  core/admin/mailu/internal/views/auth.py
  core/admin/mailu/limiter.py
  towncrier/newsfragments/2125.bugfix
Labels: priority/p1, type/bug, type/backport

#2132 Fixes #2131 - Carddav synchronization issue
  webmails/rainloop/Dockerfile
Labels: priority/p1, type/bug, type/backport

#2140 Fix 2138: Pin DANE with the full cert
  core/admin/mailu/models.py
  towncrier/newsfragments/2138.bugfix
Labels: priority/p0, type/bug, type/backport

#2141 update roundcube to 1.5.2 (security fix)
  towncrier/newsfragments/2141.bugfix
  webmails/roundcube/Dockerfile
Labels: priority/p1, type/security, type/backport

#2149 fix 2147: MESSAGE_SIZE_LIMIT wasn't working
  core/nginx/conf/nginx.conf
Labels: priority/p0, type/bug, type/backport

#2150 fix 2145: exceptions may be thrown when login is invalid or rate-limits exceeded
  core/admin/mailu/internal/views/auth.py
Labels: priority/p1, type/bug, type/backport

#2158 supply missing fields argument
  core/admin/mailu/sso/views/base.py
Labels: priority/p1, type/bug, type/backport

#2144 Enable unbound by default, warn if the DNS resolver doesn't work
  core/admin/start.py
  setup/flavors/compose/docker-compose.yml
  setup/templates/steps/compose/03_expose.html
  tests/compose/core/docker-compose.yml
  tests/compose/fetchmail/docker-compose.yml
  tests/compose/filters/docker-compose.yml
  tests/compose/rainloop/docker-compose.yml
  tests/compose/roundcube/docker-compose.yml
  tests/compose/webdav/docker-compose.yml
  towncrier/newsfragments/2135.bugfix
Labels: priority/p2, type/bug, type/backport

#2171 fixed plugin path
  webmails/roundcube/start.py
Labels: priority/p1, type/bug, type/backport

#2177 Update start.py to fix the resolver test
  core/admin/start.py
Labels: priority/p1, type/bug, type/backport

#2179 Fix resolver
  core/admin/mailu/models.py
  core/admin/mailu/utils.py
Labels: priority/p1, type/bug, type/backport

#2161 fix typo
  docs/compose/setup.rst
Labels: priority/p2, type/enhancement

#2190 Tag for release is correctly tagged to branch x.y.
  .github/workflows/CI.yml
  towncrier/newsfragments/2124.bugfix
Labels: priority/p0, type/bug, type/backport

#2193 Update php.ini
  towncrier/newsfragments/2193.bugfix
  webmails/rainloop/defaults/php.ini
Labels: priority/p2, type/bug
