Repository Mailu/Mailu, pull requests merged in 2022-08, with the labels that each got.

#2397 Fix resolving alias addresses for postfix when target is a punycode domain
  core/admin/mailu/internal/views/postfix.py
  core/admin/mailu/models.py
Labels: priority/p1, type/bug, type/backport

#2357 Switch to ffdhe3072 to enable RFC 7919
  core/nginx/conf/dhparam.pem
  towncrier/newsfragments/2357.misc
Labels: priority/p2, type/security, type/enhancement, type/backport

#2221 Add support for custom NGINX config
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/2221.feature
Labels: type/feature

#2403 Feature: switch CI/CD from build to buildx
  .github/workflows/CI.yml
  .github/workflows/arm.yml
  .github/workflows/build_test_deploy.yml
  .github/workflows/x64.yml
  core/admin/Dockerfile
  core/dovecot/Dockerfile
  core/postfix/Dockerfile
  docs/arm_images.rst
  docs/contributors/environment.rst
  docs/index.rst
  docs/rpi_build.rst
  docs/setup.rst
  tests/build.hcl
  tests/build.yml
  tests/build_arm.sh
  tests/compose/core/docker-compose.yml
  tests/compose/fetchmail/docker-compose.yml
  tests/compose/filters/docker-compose.yml
  tests/compose/roundcube/docker-compose.yml
  tests/compose/snappymail/docker-compose.yml
  tests/compose/webdav/docker-compose.yml
  tests/deploy.sh
  tests/deploy_to_pi.sh
  towncrier/newsfragments/2383.misc
  webmails/roundcube/Dockerfile
Labels: type/feature

#2421 Put ipv6 resolver address in square brackets
  core/nginx/config.py
Labels: priority/p1, type/bug

#2422 Build wheels only if we have to.
  core/admin/Dockerfile
  core/admin/requirements-prod.txt
  core/admin/requirements.txt
  core/postfix/Dockerfile
  tests/compose/test.py
Labels: type/enhancement

#2430 Prevent signups for accounts where an alias exists
  core/admin/mailu/ui/views/users.py
  towncrier/newsfragments/2429.feature
Labels: priority/p1, type/feature, type/backport

#2437 Fix mysql
  core/admin/mailu/configuration.py
  towncrier/newsfragments/2432.bugfix
Labels: priority/p1, type/bug

#2440 The ARM wheels don't work
  core/admin/Dockerfile
  core/postfix/Dockerfile
Labels: type/bug
