Repository Mailu/Mailu, pull requests merged in 2022-03, with the labels that each got.

#2265 Prevent an exception from being thrown if the username isn't an email address
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
  core/admin/mailu/internal/views/postfix.py
Labels: priority/p2, type/enhancement

#2275 Fix2274: Inbound emails are rejected
  core/admin/mailu/internal/views/auth.py
Labels: priority/p0, type/bug

#2282 Fixed typo in Traefik reverse proxy docs
  docs/reverse.rst
Labels: priority/p2, type/backport

#2277 Update RainLoop application.ini
  webmails/rainloop/defaults/application.ini
Labels: priority/p2, type/bug

#2255 Create a polite and turtle delivery queue to accommodate destinations that expect emails to be sent slowly
  core/postfix/conf/main.cf
  core/postfix/conf/master.cf
  core/postfix/start.py
  docs/faq.rst
  towncrier/newsfragments/2213.feature
Labels: priority/p2, type/feature

#2284 Fixing AUTH_RATELIMIT_IP not working on imap/pop3/smtp
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
  towncrier/newsfragments/2284.bugfix
Labels: priority/p1, type/security, type/backport

#2290 rspamd may trigger HFILTER_HOSTNAME_UNKNOWN if part of the delivery chain is using ipv6
  core/nginx/conf/nginx.conf
  setup/templates/steps/compose/03_expose.html
  towncrier/newsfragments/2260.bugfix
Labels: priority/p2, type/bug, type/backport

#2276 Autoconfig of email clients
  README.md
  core/admin/mailu/internal/views/__init__.py
  core/admin/mailu/internal/views/autoconfig.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/templates/client.html
  core/admin/mailu/ui/templates/domain/details.html
  core/admin/requirements-prod.txt
  core/admin/requirements.txt
  core/nginx/conf/nginx.conf
  core/nginx/letsencrypt.py
  docs/faq.rst
  docs/index.rst
  docs/reverse.rst
  towncrier/newsfragments/224.feature
Labels: priority/p2, type/feature, review/need2
