Repository Mailu/Mailu, pull requests merged in 2023-08, with the labels that each got.

#2894 fix fail2ban regexp
  docs/faq.rst
Labels: type/documentation

#2895 Avoid a stack-trace when the ratelimit is hit
  core/admin/mailu/internal/nginx.py
Labels: priority/p1, type/bug

#2896 Update python deps to fix CVEs and build
  core/base/requirements-prod.txt
Labels: type/security, type/backport, dependencies

#2898 take care of sieve too
  core/admin/mailu/internal/nginx.py
Labels: type/bug

#2893 bugfix for gpg execution with roundcube
  towncrier/newsfragments/2892.bugfix
  webmails/snuffleupagus.rules
Labels: priority/p1, type/bug, type/backport

#2909 Prevent rspamc zombies, ensure that triggering learn-spam works
  core/dovecot/conf/dovecot.conf
  core/dovecot/conf/ham.script
  core/dovecot/conf/spam.script
  towncrier/newsfragments/2908.bugfix
Labels: priority/p1, type/bug, type/backport

#2911 We also need a wait now that we capture stdin
  core/dovecot/conf/ham.script
  core/dovecot/conf/spam.script
Labels: priority/p1, type/bug, type/backport

#2901 Force pw change
  core/admin/mailu/api/v1/user.py
  core/admin/mailu/manage.py
  core/admin/mailu/models.py
  core/admin/mailu/sso/forms.py
  core/admin/mailu/sso/templates/pw_change.html
  core/admin/mailu/sso/views/base.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/user/create.html
  core/admin/mailu/ui/views/users.py
  core/admin/migrations/versions/0ba45693748d_.py
  towncrier/newsfragments/2877.feature
Labels: priority/p2, type/security, type/feature

#2810 Database migration documentation fixes
  docs/configuration.rst
  docs/database.rst
Labels: type/documentation

#2903 Make traefik work
  core/admin/mailu/internal/views/auth.py
  core/nginx/conf/nginx.conf
  core/nginx/dovecot/proxy.conf
  core/nginx/letsencrypt.py
  docs/compose/traefik/docker-compose.yml
  docs/compose/traefik/traefik.toml
  docs/reverse.rst
Labels: priority/p1, type/enhancement

#2924 Remove the usage of capabilities, use port 8080 for admin
  core/admin/Dockerfile
  core/admin/start.py
  core/base/Dockerfile
  core/dovecot/conf/dovecot.conf
  core/dovecot/start.py
  core/nginx/conf/nginx.conf
  core/nginx/dovecot/login.lua
  core/nginx/dovecot/proxy.conf
  core/postfix/start.py
  core/rspamd/conf/arc.conf
  core/rspamd/conf/dkim_signing.conf
  core/rspamd/conf/multimap.conf
  core/rspamd/conf/whitelist.conf
  core/rspamd/start.py
  docs/faq.rst
  optional/fetchmail/fetchmail.py
  towncrier/newsfragments/2906.bugfix
Labels: priority/p1, type/bug, type/backport

#2929 Maybe fix fetchmail when used with pop3
  optional/fetchmail/fetchmail.py
  towncrier/newsfragments/2928.bugfix
Labels: priority/p1, type/bug, type/backport
