Repository Mailu/Mailu, pull requests merged in 2023-02, with the labels that each got.

#2650 Tell roundcube that sieve scripts should be utf8 encoded
  towncrier/newsfragments/2650.bugfix
  webmails/roundcube/config/config.inc.php
Labels: priority/p1, type/bug

#2649 Backports
  core/admin/assets/app.js
  core/admin/mailu/ui/templates/domain/create.html
  core/admin/mailu/ui/templates/user/create.html
  towncrier/newsfragments/2649.bugfix
  webmails/roundcube/config.inc.php
Labels: priority/p1, type/bug

#2651 Allow + in localpart of addresses to forward to
  core/admin/mailu/ui/forms.py
  towncrier/newsfragments/1236.bugfix
Labels: priority/p2, type/bug, type/backport

#2656 Zero quota is unlimited
  webmails/roundcube/config/config.inc.php
Labels: type/bug

#2640 Add env variable to set sieve_vacation_to_header_ignore_envelope
  core/dovecot/conf/dovecot.conf
  towncrier/newsfragments/2640.bugfix
Labels: priority/p2, type/enhancement

#2646 Smarter ratelimit
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/views/auth.py
  core/admin/mailu/limiter.py
  core/admin/mailu/sso/views/base.py
  docs/configuration.rst
  setup/flavors/compose/mailu.env
  setup/templates/steps/config.html
  towncrier/newsfragments/2644.misc
Labels: priority/p2, type/enhancement

#2659 Doh.
  core/admin/mailu/internal/views/auth.py
Labels: priority/p0, type/bug

#2670 Patch for CVE-2023-20032
  optional/clamav/Dockerfile
  towncrier/newsfragments/2669.bugfix
Labels: priority/p0, type/security

#2667 Alpine 3.17.2
  core/base/Dockerfile
  towncrier/newsfragments/2666.misc
Labels: priority/p0, type/security, type/bug
