Repository Mailu/Mailu, pull requests merged in 2023-06, with the labels that each got.

#2815 Update version to 2.+ in release template
  RELEASE_TEMPLATE.md
Labels: type/documentation

#2847 Use dovecot-proxy
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
  core/admin/mailu/models.py
  core/dovecot/Dockerfile
  core/dovecot/conf/dovecot.conf
  core/nginx/Dockerfile
  core/nginx/conf/nginx.conf
  core/nginx/dovecot/login.lua
  core/nginx/dovecot/proxy.conf
  core/postfix/conf/main.cf
  core/postfix/conf/master.cf
  optional/fetchmail/fetchmail.py
  towncrier/newsfragments/2847.misc
  webmails/roundcube/config/config.inc.php
  webmails/snappymail/defaults/default.json
Labels: type/enhancement

#2869 increase the number of postfix workers
  core/postfix/conf/master.cf
  towncrier/newsfragments/2869.bugfix
Labels: priority/p1, type/bug, type/backport

#2871 Document that the default config for netplan is broken
  docs/faq.rst
  optional/unbound/start.py
Labels: type/documentation

#2866 Improve tokens (add ipranges)
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/token/list.html
  core/admin/mailu/ui/views/tokens.py
  core/admin/mailu/utils.py
  core/admin/migrations/versions/6b8f5e8caaa9_.py
  docs/webadministration.rst
  towncrier/newsfragments/2852.misc
Labels: type/security, type/enhancement

#2873 Fix issue #2811. Clamav Healthcheck created zombie processes
  optional/clamav/Dockerfile
  towncrier/newsfragments/2811.bugfix
Labels: type/bug, type/backport

#2677 Apply DEFAULT_QUOTA to user creation admin ui page
  core/admin/mailu/ui/views/users.py
  docs/configuration.rst
Labels: type/bug
