Repository Mailu/Mailu, pull requests merged in 2023-01, with the labels that each got.

#2611 Fix authenticated submission
  core/nginx/conf/nginx.conf
  core/postfix/conf/master.cf
  towncrier/newsfragments/2608.fix
Labels: priority/p0, type/bug

#2615 Fix snappymail
  core/postfix/conf/main.cf
  core/postfix/conf/master.cf
  webmails/snuffleupagus.rules
Labels: priority/p1, type/bug

#2621 Upgrade to snuffleupagus 0.9.0
  core/base/Dockerfile
  towncrier/newsfragments/2618.misc
  webmails/snuffleupagus.rules
Labels: priority/p2, type/enhancement

#2622 Fix smtplib.LMTP wrong argument name: ip -> host
  core/admin/mailu/models.py
Labels: type/bug

#2464 Introduce RESTful API
  .gitignore
  core/admin/mailu/__init__.py
  core/admin/mailu/api/__init__.py
  core/admin/mailu/api/common.py
  core/admin/mailu/api/v1/__init__.py
  core/admin/mailu/api/v1/alias.py
  core/admin/mailu/api/v1/domains.py
  core/admin/mailu/api/v1/relay.py
  core/admin/mailu/api/v1/user.py
  core/admin/mailu/configuration.py
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
  core/nginx/conf/nginx.conf
  docs/api.rst
  docs/cli.rst
  docs/configuration.rst
  docs/faq.rst
  docs/index.rst
  docs/requirements.txt
  towncrier/newsfragments/445.feature
Labels: type/feature, review/need2, python

#2625 Disable fetchmail
  core/admin/mailu/ui/templates/user/list.html
Labels: type/bug

#2627 Add SUBNET6 to places where SUBNET is used
  core/admin/mailu/configuration.py
  core/postfix/conf/main.cf
  core/rspamd/conf/worker-controller.inc
Labels: type/bug

#2604 Really fix creation of deep structures using import in update mode
  core/admin/mailu/schemas.py
Labels: priority/p0, type/bug, type/backport, python

#2631 Restful api finishing touches
  core/admin/mailu/__init__.py
  core/admin/mailu/api/__init__.py
  core/base/requirements-prod.txt
  docs/api.rst
  docs/configuration.rst
  setup/flavors/compose/mailu.env
  setup/static/render.js
  setup/templates/steps/config.html
Labels: type/enhancement, dependencies, python, type/documentation

#2606 Modify the healtchecks to make them disapear from the logs.
  core/admin/Dockerfile
  core/admin/mailu/__init__.py
  core/admin/start.py
  core/dovecot/Dockerfile
  core/dovecot/conf/dovecot.conf
  core/postfix/conf/rsyslog.conf
  towncrier/newsfragments/2606.misc
Labels: priority/p2, type/enhancement

#2633 Don't apply antispoof rules on locally generated emails
  core/rspamd/conf/force_actions.conf
  core/rspamd/conf/local_subnet.map
  core/rspamd/conf/multimap.conf
  towncrier/newsfragments/2633.bugfix
Labels: priority/p1, type/bug

#2634 Upgrade webmails
  towncrier/newsfragments/2634.misc
  webmails/Dockerfile
  webmails/nginx-webmail.conf
  webmails/roundcube/config/config.inc.php
  webmails/start.py
Labels: priority/p2, type/enhancement

#2630 Improved IPv6 support #2
  core/admin/start.py
  core/nginx/conf/nginx.conf
  core/oletools/Dockerfile
  core/postfix/conf/main.cf
  docs/faq.rst
  optional/radicale/radicale.conf
  setup/flavors/compose/docker-compose.yml
  towncrier/2630.feature
  webmails/nginx-webmail.conf
Labels: type/bug, type/enhancement, type/documentation

#2637 Upgrade to alpine 3.17.1
  core/base/Dockerfile
  towncrier/newsfragments/2636.enhancement
Labels: priority/p2, type/enhancement

#2636 Fix out of office replies
  core/rspamd/conf/options.inc
  towncrier/newsfragments/2635.bugfix
Labels: priority/p2, type/bug

#2632 Interface cosmetics
  core/admin/assets/assets/app.css
  core/admin/assets/assets/app.js
  core/admin/mailu/configuration.py
  core/admin/mailu/ui/templates/admin/list.html
  core/admin/mailu/ui/templates/alias/list.html
  core/admin/mailu/ui/templates/alternative/list.html
  core/admin/mailu/ui/templates/base.html
  core/admin/mailu/ui/templates/domain/create.html
  core/admin/mailu/ui/templates/domain/list.html
  core/admin/mailu/ui/templates/fetch/list.html
  core/admin/mailu/ui/templates/manager/list.html
  core/admin/mailu/ui/templates/token/list.html
  core/admin/mailu/ui/templates/user/create.html
  core/admin/mailu/ui/templates/user/list.html
  webmails/roundcube/login/skins/elastic/mailu.css
Labels: type/bug, type/enhancement

#2639 Update demo docs with new capabilities
  docs/demo.rst
Labels: priority/p2, type/documentation

#2638 further finishing touches for restful api
  core/nginx/config.py
  docs/reverse.rst
  setup/static/render.js
  setup/templates/steps/config.html
Labels: priority/p2, type/bug, python, type/documentation
