Repository Mailu/Mailu, pull requests merged in 2023-11, with the labels that each got.

#3023 Add zonefile download
  core/admin/mailu/models.py
  core/admin/mailu/translations/en/LC_MESSAGES/messages.po
  core/admin/mailu/ui/templates/domain/details.html
  core/admin/mailu/ui/views/domains.py
  docs/webadministration.rst
  towncrier/newsfragments/3023.feature
Labels: type/enhancement, python

#3041 SECURITY FIX: Update to Roundcube 1.6.5
  towncrier/newsfragments/3024.misc
  webmails/Dockerfile
Labels: priority/p1, type/security, type/bug, type/backport

#3033 Enable snowball on FTS
  core/dovecot/conf/dovecot.conf
  core/rspamd/conf/external_services.conf
  towncrier/newsfragments/2977.misc
  webmails/roundcube/config/config.inc.php
  webmails/snappymail/defaults/default.json
Labels: priority/p2, type/enhancement

#3049 Ensure that we do not silently discard PUAs flagged by clamav
  core/admin/mailu/internal/templates/default.sieve
  core/rspamd/conf/force_actions.conf
  tests/compose/filters/01_email_test.sh
  tests/compose/filters/PotentiallyUnwanted.exe_
  towncrier/newsfragments/3048.bugfix
Labels: type/bug, type/backport

#3055 Doh
  core/rspamd/conf/force_actions.conf
Labels: type/backport

#3057 Retry up to 5 times if not ready
  tests/compose/filters/02_email_antispam.sh
  tests/email_test.py
Labels: priority/p1, type/bug

#3025 Fix SETUP generating invalid files.
  setup/flavors/compose/mailu.env
  setup/server.py
  setup/static/jquery.min.js
  setup/static/render.js
  setup/templates/base.html
  setup/templates/steps/compose/02_services.html
  setup/templates/steps/compose/03_expose.html
  setup/templates/steps/config.html
  towncrier/newsfragments/2890.bugfix
Labels: priority/p1, type/bug

#3076 Slow down the turtle policy
  core/postfix/conf/master.cf
  towncrier/newsfragments/3075.bugfix
Labels: priority/p2
