Repository Mailu/Mailu, pull requests merged in 2023-05, with the labels that each got.

#2808 Ensure SCAN_MACROS works
  core/rspamd/conf/composites.conf
  core/rspamd/conf/external_services.conf
  core/rspamd/conf/external_services_group.conf
  core/rspamd/start.py
  towncrier/newsfragments/2805.bugfix
Labels: priority/p1, type/bug, type/backport

#2823 Don't send ooo messages to noreply@
  core/admin/mailu/internal/templates/default.sieve
  towncrier/newsfragments/2823.bugfix
Labels: priority/p2, type/bug

#2829 update docs
  docs/compose/requirements.rst
  docs/faq.rst
  towncrier/newsfragments/2829.misc
Labels: priority/p2, type/backport, type/documentation

#2790 Implement managesieve support
  README.md
  core/admin/mailu/internal/nginx.py
  core/dovecot/conf/dovecot.conf
  core/nginx/Dockerfile
  core/nginx/certwatcher.py
  core/nginx/conf/nginx.conf
  core/nginx/config.py
  core/nginx/dovecot/login.lua
  core/nginx/dovecot/proxy.conf
  core/nginx/start.py
  docs/compose/requirements.rst
  docs/index.rst
  setup/flavors/compose/docker-compose.yml
  tests/compose/core/05_connectivity.py
  tests/compose/core/docker-compose.yml
  tests/requirements.txt
  towncrier/newsfragments/81.feature
  webmails/roundcube/config/config.inc.php
  webmails/snappymail/defaults/default.json
Labels: priority/p2, type/feature

#2838 Authentication failed for email clients when the password contained a non latin-1 character.
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
  tests/compose/core/00_create_users.sh
  tests/compose/core/05_connectivity.py
  towncrier/newsfragments/2837.bugfix
Labels: priority/p1, type/bug, type/backport
