Repository Mailu/Mailu, pull requests merged in 2023-04, with the labels that each got.

#2734 Fix setup
  docs/compose/.env
  docs/compose/docker-compose.yml
  docs/compose/traefik/docker-compose.yml
  docs/faq.rst
  setup/flavors/compose/docker-compose.yml
  setup/flavors/compose/mailu.env
  towncrier/newsfragments/2734.misc
Labels: priority/p0, type/bug

#2733 Ensure we always ask for the existing password before allowing a change
  core/admin/mailu/ui/forms.py
  core/admin/mailu/ui/templates/sidebar.html
  core/admin/mailu/ui/views/users.py
  towncrier/newsfragments/2733.misc
Labels: priority/p1, type/security

#2738 Make ratelimit exemptions less generous
  core/admin/mailu/internal/views/auth.py
Labels: priority/p0, type/security

#2745 Fix tag-release step in workflow which prevented github releases from being created automatically
  .github/workflows/build_test_deploy.yml
  docs/api.rst
  docs/configuration.rst
  docs/faq.rst
  docs/releases.rst
  towncrier/newsfragments/2744.misc
Labels: type/backport

#2748 Improve ci by using intermediate images
  .github/workflows/build_test_deploy.yml
  tests/build-ci.hcl
  towncrier/newsfragments/2748.misc
Labels: type/backport

#2752 Fix config-import. Config with dkim key could not be imported.
  core/admin/mailu/schemas.py
  towncrier/newsfragments/2747.bugfix
Labels: type/backport

#2756 POP3 is broken
  .github/workflows/build_test_deploy.yml
  core/dovecot/conf/dovecot.conf
  core/postfix/conf/master.cf
  tests/compose/core/05_connectivity.py
  towncrier/newsfragments/2756.bugfix
Labels: priority/p0, type/bug, type/backport

#2767 Fix #2720: make letsencrypt work when reverse proxies are misconfigured
  core/nginx/conf/nginx.conf
  optional/fetchmail/Dockerfile
  towncrier/newsfragments/2720.bugfix
Labels: priority/p2, type/bug, type/backport

#2777 Whitelist all mailso* stream types in snuffleupagus for snappymail
  towncrier/newsfragments/2776.bugfix
  webmails/snuffleupagus.rules
Labels: priority/p0, type/bug, type/backport

#2771 Sanitize logs as appropriate
  core/admin/start.py
  core/base/libs/socrate/socrate/system.py
  core/dovecot/start.py
  core/nginx/start.py
  core/postfix/Dockerfile
  core/postfix/conf/logrotate.conf
  core/postfix/conf/master.cf
  core/postfix/conf/rsyslog.conf
  core/postfix/start.py
  core/rspamd/start.py
  optional/clamav/start.py
  optional/radicale/Dockerfile
  optional/unbound/start.py
  towncrier/newsfragments/2644.misc
  webmails/start.py
Labels: priority/p2, type/enhancement, type/backport

#2794 Fix logs in the SMTP container
  core/dovecot/Dockerfile
  core/dovecot/conf/dovecot.conf
  core/dovecot/start.py
  core/postfix/Dockerfile
  core/postfix/conf/main.cf
  core/postfix/conf/master.cf
  core/postfix/start.py
  docs/configuration.rst
  setup/flavors/compose/mailu.env
  towncrier/newsfragments/2793.bugfix
Labels: priority/p0, type/bug, type/backport

#2799 Fix roundcube's spellchecker
  docs/faq.rst
  towncrier/newsfragments/2798.bugfix
  webmails/roundcube/config/config.inc.php
Labels: priority/p1, type/bug, type/backport
