Repository Mailu/Mailu, pull requests merged in 2023-10, with the labels that each got.

#2956 Remove the version pinning on hardened malloc
  core/base/Dockerfile
  towncrier/newsfragments/2955.misc
Labels: priority/p1, type/bug, type/backport

#2962 Fix letsencrypt on master
  core/nginx/letsencrypt.py
  towncrier/newsfragments/2962.bugfix
Labels: priority/p1, type/bug

#2958 Upgrade to alpine 3.18.4
  core/base/Dockerfile
  core/rspamd/start.py
  towncrier/newsfragments/2934.bugfix
  webmails/Dockerfile
Labels: priority/p1, type/bug, type/backport

#2961 Hardened malloc was not disabled for oletools when an CPU with missing flags is used
  core/base/Dockerfile
  core/base/libs/socrate/socrate/system.py
  core/oletools/Dockerfile
  core/oletools/start.py
  docs/compose/.env
  docs/compose/setup.rst
  towncrier/newsfragments/2959.bugfix
  webmails/Dockerfile
Labels: priority/p0, type/bug, type/backport

#2950 Upgrade snuffleupagus
  core/base/Dockerfile
  towncrier/newsfragments/2950.misc
  webmails/snuffleupagus.rules
Labels: priority/p2

#2969 Upgrade dovecot: fix proxying ipv6 via xclient
  core/dovecot/Dockerfile
  towncrier/newsfragments/2918.misc
Labels: priority/p1, type/bug

#2975 Forbidden_file_extension.map could not be overridden.
  core/rspamd/start.py
  towncrier/newsfragments/2937.bugfix
Labels: priority/p1, type/bug, type/backport

#2979 Enhance RESTful API user retrieval with quota used bytes.
  core/admin/mailu/api/v1/user.py
  towncrier/newsfragments/2824.feature
Labels: priority/p2, type/enhancement

#2972 switch to fts-flatcurve
  README.md
  core/admin/mailu/configuration.py
  core/admin/run_dev.sh
  core/base/Dockerfile
  core/dovecot/Dockerfile
  core/dovecot/conf/dovecot.conf
  docs/configuration.rst
  docs/index.rst
  setup/flavors/compose/docker-compose.yml
  setup/flavors/compose/mailu.env
  setup/templates/steps/compose/02_services.html
  towncrier/newsfragments/2971.bugfix
Labels: priority/p2, type/bug

#2985 Roundcube 1.6.4
  core/admin/start.py
  docs/faq.rst
  towncrier/newsfragments/2985.misc
  webmails/Dockerfile
Labels: priority/p1, type/security, type/backport

#2981 Further improvements to fts
  core/dovecot/conf/dovecot.conf
  setup/flavors/compose/docker-compose.yml
  towncrier/newsfragments/2971.bugfix
Labels: priority/p2, type/enhancement

#2982 Switch to upstream's clamav image
  .github/workflows/build_test_deploy.yml
  optional/clamav/Dockerfile
  optional/clamav/README.md
  optional/clamav/conf/clamd.conf
  optional/clamav/conf/freshclam.conf
  optional/clamav/start.py
  setup/flavors/compose/docker-compose.yml
  tests/build-ci.hcl
  tests/build.hcl
  tests/compose/filters/docker-compose.yml
  towncrier/newsfragments/2059.misc
Labels: priority/p2, type/enhancement

#2990 Fix letsencrypt on master
  ISSUE_TEMPLATE.md
  core/admin/start.py
  core/nginx/letsencrypt.py
  towncrier/newsfragments/2990.misc
Labels: priority/p0, type/bug

#2991 Remove IMAP ID capability from nginx
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/2938-remove-id.bugfix
Labels: priority/p2, type/bug

#3009 fix CI on master
  core/dovecot/Dockerfile
Labels: priority/p0

#3007 Introduce AUTH_REQUIRE_TOKENS
  core/admin/mailu/configuration.py
  core/admin/mailu/internal/nginx.py
  docs/configuration.rst
  towncrier/newsfragments/3007.misc
Labels: priority/p2, type/security, type/enhancement

#3003 Update documentation
  README.md
  core/admin/mailu/ui/templates/client.html
  docs/antispam.rst
  docs/compose/requirements.rst
  docs/configuration.rst
  docs/contributors/guidelines.rst
  docs/contributors/memo.rst
  docs/contributors/workflow.rst
  docs/database.rst
  docs/faq.rst
  docs/index.rst
  docs/mailu-network-diagram.ipynb
  docs/releases.rst
  docs/reverse.rst
  docs/webadministration.rst
  setup/templates/steps/compose/02_services.html
  setup/templates/steps/config.html
Labels: type/documentation

#3008 Fix issues with log filter and remove POSTFIX_LOG_FILE
  core/base/libs/socrate/socrate/system.py
  core/dovecot/start.py
  core/nginx/start.py
  core/postfix/start.py
  docs/configuration.rst
  docs/faq.rst
  setup/flavors/compose/docker-compose.yml
  towncrier/newsfragments/2939.bugfix
Labels: priority/p1, type/bug, type/documentation

#3010 Long term solution for helm-charts
  core/admin/mailu/internal/nginx.py
  core/admin/start.py
Labels: priority/p1

#3029 Update dependencies docs image and fix non-working badge
  core/rspamd/conf/antivirus.conf
  docs/Dockerfile
  docs/index.rst
  docs/requirements.txt
Labels: priority/p2, type/bug, dependencies
