Repository Mailu/Mailu, pull requests merged in 2023-03, with the labels that each got.

#2665 Update to docker compose v2
  CHANGELOG.md
  ISSUE_TEMPLATE.md
  RELEASE_TEMPLATE.md
  design/mailu-directory-structure.md
  docs/antispam.rst
  docs/cli.rst
  docs/compose/.env
  docs/compose/requirements.rst
  docs/compose/setup.rst
  docs/contributors/environment.rst
  docs/database.rst
  docs/faq.rst
  docs/maintain.rst
  docs/releases.rst
  docs/setup.rst
  setup/flavors/compose/mailu.env
  setup/flavors/compose/setup.html
  tests/compose/core/00_create_users.sh
  tests/compose/core/02_forward_test.sh
  tests/compose/core/03_alias_test.sh
  tests/compose/core/04_reply_test.sh
  tests/compose/core/mailu.env
  tests/compose/fetchmail/mailu.env
  tests/compose/filters/00_create_users.sh
  tests/compose/filters/mailu.env
  tests/compose/test.py
  tests/compose/webdav/mailu.env
  tests/compose/webmail/01_ensure_admin_unreachable.sh
  tests/compose/webmail/docker-compose.yml
  tests/compose/webmail/mailu.env
Labels: type/documentation

#2660 Fail2ban update
  docs/faq.rst
  towncrier/newsfragments/2660.misc
Labels: type/security, type/documentation

#2694 fix #2693
  towncrier/newsfragments/2693.bugfix
  webmails/snuffleupagus.rules
Labels: priority/p1, type/bug

#2702 Upgrade snappymail to v2.26.4
  towncrier/newsfragments/2698.misc
  webmails/Dockerfile
Labels: priority/p2, type/enhancement

#2566 Make it clear that we don't delete users
  core/admin/mailu/manage.py
  core/admin/mailu/ui/templates/user/list.html
  core/admin/mailu/ui/views/users.py
  docs/cli.rst
  docs/faq.rst
  docs/webadministration.rst
  scripts/purge_user.sh
  towncrier/newsfragments/2566.misc
Labels: type/security, type/bug

#2703 Paranoia: drop the headers we don't use
  core/nginx/conf/proxy.conf
Labels: priority/p2, type/security

#2717 nginx: Allow HTTP and/or TCP ports to accept the PROXY protocol
  core/nginx/Dockerfile
  core/nginx/conf/nginx.conf
  core/nginx/conf/proxy.conf
  docs/configuration.rst
  towncrier/newsfragments/2717.feature
Labels: type/feature

#2725 Fix access to radicale
  core/nginx/conf/proxy.conf
  optional/radicale/radicale.conf
  setup/flavors/compose/docker-compose.yml
Labels: priority/p0, type/bug
