Repository Mailu/Mailu, pull requests merged in 2024-02, with the labels that each got.

#3175 update Simplified Chinese translation
  core/admin/mailu/translations/zh/LC_MESSAGES/messages.po
  towncrier/newsfragments/3175.bugfix
Labels: type/enhancement

#3178 Fix ooo/sieve when proxy protocol is in use
  core/dovecot/conf/dovecot.conf
  towncrier/newsfragments/3172.bugfix
Labels: priority/p1, type/bug

#3138 Update dependencies and re-enable flask toolbar
  core/admin/mailu/debug.py
  core/admin/mailu/models.py
  core/admin/mailu/sso/views/base.py
  core/admin/mailu/utils.py
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
Labels: dependencies, python
