Repository Mailu/Mailu, pull requests merged in 2024-05, with the labels that each got.

#3239 Fix purge_user.sh
  scripts/purge_user.sh
  towncrier/newsfragments/3238.bugfix
Labels: priority/p1, type/bug, type/backport

#3251 Fix CVE-2024-1135
  core/base/requirements-prod.txt
  towncrier/newsfragments/3251.bugfix
Labels: priority/p0, type/security, type/backport

#3235 Tweaks to logging
  core/admin/mailu/__init__.py
  setup/flavors/compose/mailu.env
Labels: type/security

#3261 Fix #3260: double-quotes should be escaped/allowed in ooo
  core/admin/mailu/internal/templates/default.sieve
  towncrier/newsfragments/3260.bugfix
Labels: priority/p2, type/bug

#3267 Update Roundcube 1.6.7 due to XSS vulnerabilities
  towncrier/newsfragments/3261.bugfix
  webmails/Dockerfile
Labels: priority/p0, type/security, type/backport

#3269 Upgrade Tika and switch to the upstream image
  setup/flavors/compose/docker-compose.yml
  tests/requirements.txt
Labels: type/bug

#3270 Use the new image name for Tika
  setup/flavors/compose/docker-compose.yml
Labels: type/bug

#3279 Alpine 3.20
  core/base/Dockerfile
  core/dovecot/Dockerfile
  core/dovecot/conf/dovecot.conf
  towncrier/newsfragments/3279.misc
  webmails/Dockerfile
Labels: type/enhancement
