Repository Mailu/Mailu, pull requests merged in 2024-08, with the labels that each got.

#3358 Update 3rd party deps
  core/admin/mailu/models.py
  docs/antispam.rst
  setup/flavors/compose/docker-compose.yml
  towncrier/newsfragments/3347.bugfix
  webmails/Dockerfile
Labels: type/security, type/backport

#3366 Fix #3364
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/internal/views/auth.py
  core/nginx/dovecot/login.lua
  tests/compose/core/00_create_users.sh
  tests/compose/core/05_connectivity.py
  towncrier/newsfragments/3364.bugfix
Labels: priority/p0, type/security, type/bug, type/backport

#3308 Update network graph
  .gitignore
  core/base/libs/socrate/socrate/system.py
  core/nginx/config.py
  docs/Dockerfile
  docs/contributors/firewalling.rst
  docs/index.rst
  docs/mailu-network-diagram.dot
  docs/mailu-network-diagram.ipynb
  optional/fetchmail/fetchmail.py
Labels: type/backport, type/documentation

#3350 Feature: dkim for alternative domains
  core/admin/mailu/internal/views/rspamd.py
  core/admin/mailu/models.py
  core/admin/mailu/translations/de/LC_MESSAGES/messages.po
  core/admin/mailu/ui/templates/domain/details.html
  towncrier/newsfragments/3350.feature
Labels: priority/p2, type/feature

#3376 fix: PATCH /user will overwrite existing "forward_destination"
  core/admin/mailu/api/v1/user.py
  towncrier/newsfragments/3374.bugfix
Labels: type/bug

#3386 Update snuffleupagus rules
  towncrier/newsfragments/3384.bugfix
  webmails/snuffleupagus.rules
Labels: priority/p2, type/security, type/backport
