Repository Mailu/Mailu, pull requests merged in 2024-01, with the labels that each got.

#3120 Update the traefik doc
  docs/reverse.rst
Labels: type/documentation

#3132 Fix 3129, thanks to Games-Crack
  optional/traefik-certdumper/run.sh
  towncrier/newsfragments/3129.bugfix
Labels: priority/p1, type/bug, type/backport

#3136 Roundcube 1.6.6
  towncrier/newsfragments/3130.misc
  webmails/Dockerfile
Labels: type/enhancement
