Repository Mailu/Mailu, pull requests merged in 2024-06, with the labels that each got.

#3221 Better PROXY_PROTOCOL
  core/dovecot/conf/dovecot.conf
  core/nginx/conf/nginx.conf
  core/nginx/conf/proxy.conf
  core/nginx/config.py
  core/nginx/dovecot/proxy.conf
  docs/compose/setup.rst
  docs/configuration.rst
  docs/reverse.rst
  tests/compose/core/mailu.env
  tests/compose/fetchmail/mailu.env
  tests/compose/filters/mailu.env
  tests/compose/webdav/mailu.env
  tests/compose/webmail/mailu.env
  towncrier/newsfragments/3061.feature
  webmails/snappymail/defaults/default.json
Labels: priority/p2, type/feature

#3295 webdav (radicale) not reachable
  optional/radicale/radicale.conf
  towncrier/newsfragments/3294.bugfix
Labels: priority/p0, type/bug, type/backport

#3299 fix warnings
  core/admin/mailu/internal/views/postfix.py
  core/admin/mailu/ui/forms.py
  core/base/libs/socrate/socrate/system.py
  core/nginx/conf/nginx.conf
  core/nginx/config.py
  docs/compose/docker-compose.yml
  docs/docker-compose.yml
  setup/docker-compose.yml
  setup/flavors/compose/docker-compose.yml
  tests/compose/api/docker-compose.yml
  tests/compose/core/docker-compose.yml
  tests/compose/fetchmail/docker-compose.yml
  tests/compose/filters/docker-compose.yml
  tests/compose/webdav/docker-compose.yml
  tests/compose/webmail/docker-compose.yml
Labels: type/backport

#3315 define client_ip variable
  core/admin/mailu/sso/views/base.py
  towncrier/newsfragments/3314.bugfix
Labels: priority/p1, type/bug, type/backport

#3313 nginx should recursively set the realip until the first no trusted ad…
  core/nginx/conf/nginx.conf
  towncrier/newsfragments/3311.bugfix
Labels: type/enhancement, type/backport

#3307 ports not in PORTS should not be bound
  core/admin/mailu/configuration.py
  core/admin/mailu/models.py
  core/nginx/dovecot/proxy.conf
  docs/configuration.rst
  towncrier/newsfragments/3307.bugfix
Labels: priority/p1, type/bug, type/backport
