Repository Mailu/Mailu, pull requests merged in 2024-03, with the labels that each got.

#3181 Ensure that nginx and dovecot are reloaded
  core/nginx/config.py
  towncrier/newsfragments/3179.bugfix
Labels: priority/p1, type/bug

#3188 Ensure we always send an ISRG root for DANE
  core/admin/assets/Dockerfile
  core/base/requirements-prod.txt
  core/nginx/conf/nginx.conf
  core/nginx/config.py
  towncrier/newsfragments/3187.bugfix
Labels: priority/p1, type/bug, type/backport

#3189 Bump tika version to 2.9.1
  core/base/Dockerfile
  setup/flavors/compose/docker-compose.yml
Labels: type/enhancement

#3184 Remove redundant variable assignment
  .github/workflows/multiarch.yml
Labels: type/enhancement

#3191 Ensure we also pin ISRG X2 in TLSA
  core/admin/mailu/api/v1/domain.py
  core/admin/mailu/models.py
  core/admin/mailu/ui/templates/domain/details.html
  core/admin/mailu/ui/views/domains.py
  towncrier/newsfragments/3191.feature
Labels: priority/p2, type/enhancement

#3165 Documentation: config-export had wrong example.
  docs/cli.rst
  docs/database.rst
Labels: type/documentation

#3200 Fix highligting disabled users
  core/admin/mailu/ui/templates/user/list.html
Labels: priority/p2, type/enhancement

#3204 Fix bug 3068. Spam messages were always marked as read.
  core/dovecot/conf/report-spam.sieve
  docs/webadministration.rst
  towncrier/newsfragments/3068.bugfix
Labels: type/backport

#3206 Fix typo in setup
  setup/templates/steps/compose/03_expose.html
Labels: type/documentation
