Repository Mailu/Mailu, pull requests merged in 2024-09, with the labels that each got.

#3407 misc fixes
  core/admin/mailu/internal/nginx.py
  core/admin/mailu/ui/views/users.py
  core/base/libs/socrate/socrate/system.py
  docs/maintain.rst
  optional/fetchmail/fetchmail.py
  towncrier/newsfragments/2296.bugfix
  towncrier/newsfragments/3272.bugfix
  towncrier/newsfragments/3379.bugfix
  towncrier/newsfragments/3401.bugfix
  towncrier/newsfragments/3403.bugfix
  towncrier/newsfragments/3405.bugfix
  webmails/nginx-webmail.conf
  webmails/snuffleupagus.rules
Labels: priority/p2, type/bug, type/backport, type/documentation

#3421 Fix 3420 - fixed syntax errors in certwatcher.py
  core/nginx/certwatcher.py
  towncrier/newsfragments/3420.bugfix
Labels: priority/p0, type/bug, type/backport, python

#3423 Fix #3411
  core/admin/mailu/models.py
  towncrier/newsfragments/3411.bugfix
Labels: priority/p1, type/bug, type/backport

#3439 fix container name
  docs/maintain.rst
Labels: priority/p2, type/documentation

#3463 Fix #3450
  core/admin/start.py
  core/base/libs/socrate/socrate/system.py
  core/dovecot/conf/dovecot.conf
  core/nginx/dovecot/proxy.conf
  docs/faq.rst
  towncrier/newsfragments/3450.bugfix
Labels: priority/p1, type/bug, type/backport

#3466 Improve as per @ghostwheel42's suggestion
  core/admin/mailu/ui/forms.py
Labels: type/enhancement

#3468 Fix overrides
  core/dovecot/conf/dovecot.conf
  core/nginx/dovecot/proxy.conf
  towncrier/newsfragments/3467.bugfix
Labels: priority/p1, type/bug, type/backport

#3465 Maybe fix #3402
  core/nginx/conf/nginx.conf
  core/nginx/letsencrypt.py
  towncrier/newsfragments/3402.bugfix
Labels: priority/p1, type/bug, type/backport

#3558 Only enable HARDENED_MALLOC with kernel 6.1+
  core/base/libs/socrate/socrate/system.py
  towncrier/newsfragments/3398.misc
Labels: type/enhancement
