Repository Mailu/Mailu, pull requests merged in 2025-02, with the labels that each got.

#3749 Ensure tests actually work
  tests/compose/core/00_create_users.sh
  tests/compose/core/01_email_test.sh
  tests/compose/core/02_forward_test.sh
  tests/compose/core/03_alias_test.sh
  tests/compose/core/04_reply_test.sh
  towncrier/newsfragments/3587.bugfix
Labels: type/bug

#3748 Bump CREDENTIAL_ROUNDS to 13
  core/admin/mailu/configuration.py
  docs/configuration.rst
  towncrier/newsfragments/1753.feature
Labels: priority/p2, type/enhancement

#3742 Fixed "core" Docker image to allow x86_32 building, updated documenta…
  core/base/Dockerfile
  docs/faq.rst
  docs/setup.rst
Labels: type/documentation

#3755 Update Roundcube to 1.6.10
  towncrier/newsfragments/3753.misc
  webmails/Dockerfile
Labels: type/backport

#3758 added idna function to perform puny encoding on IDN domains
  core/admin/mailu/internal/views/rspamd.py
  towncrier/newsfragments/3758.bugfix
Labels: priority/p1, type/bug, type/backport

#3729 Allow setting collation via env variable and add uvloop
  core/admin/mailu/configuration.py
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
  docs/faq.rst
  towncrier/newsfragments/3729.misc
Labels: priority/p2, type/enhancement
