Repository Mailu/Mailu, pull requests merged in 2025-01, with the labels that each got.

#3699 Add the mariadb connector as per 3449
  core/base/Dockerfile
  core/base/requirements-dev.txt
  core/base/requirements-prod.txt
  docs/faq.rst
  towncrier/newsfragments/3449.bugfix
Labels: priority/p1, type/bug, type/backport

#3440 Update reverse proxy documentation for using Traefik on a different host
  docs/reverse.rst
  towncrier/newsfragments/3440.doc
Labels: priority/p2, type/backport, type/documentation

#3709 Clarify ip listen address setting
  setup/templates/steps/compose/03_expose.html
  towncrier/newsfragments/3680.misc
Labels: priority/p1, type/backport, type/documentation

#3722 Ensure we always use Mailu for sending emails in thunderbird
  core/admin/mailu/internal/views/autoconfig.py
  tests/compose/core/05_connectivity.py
  tests/requirements.txt
  towncrier/newsfragments/3721.bugfix
Labels: priority/p1, type/bug, type/backport

#3735 Fix `clamav` path to allow for updates
  setup/flavors/compose/docker-compose.yml
  tests/compose/filters/docker-compose.yml
  towncrier/newsfragments/3735.bugfix
Labels: priority/p1, type/bug, type/backport

#3739 Fix the webpack build due to dependOn issue
  core/admin/assets/webpack.config.js
Labels: type/bug, type/backport
